'use strict';
/**
 * applyAuditFixes.cjs  — Priority 1 + 2 audit fixes
 * Applies all rarity corrections and new animal additions from the deep audit.
 * Run: node scripts/applyAuditFixes.cjs
 */

const fs   = require('fs');
const path = require('path');
const https = require('https');

const ROOT = path.join(__dirname, '..');

// ── load .env ──────────────────────────────────────────────────────────────
function loadEnv() {
  const env = {};
  try {
    for (const line of fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split('\n')) {
      const m = line.match(/^\s*([^#=]+?)\s*=\s*(.*?)\s*$/);
      if (m) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  } catch {}
  return env;
}
const ENV = loadEnv();

// ── load / save wildlifeCache ──────────────────────────────────────────────
function loadCache() {
  const src = fs.readFileSync(path.join(ROOT, 'src', 'data', 'wildlifeCache.js'), 'utf8');
  const cjs = src
    .replace('export const WILDLIFE_CACHE_BUILT_AT', 'const WILDLIFE_CACHE_BUILT_AT')
    .replace('export const WILDLIFE_CACHE', 'const WILDLIFE_CACHE')
    + '\nmodule.exports = { WILDLIFE_CACHE, WILDLIFE_CACHE_BUILT_AT };';
  const tmp = path.join(__dirname, '_fix_cache_tmp.cjs');
  fs.writeFileSync(tmp, cjs);
  const mod = require(tmp);
  fs.unlinkSync(tmp);
  return { cache: mod.WILDLIFE_CACHE, builtAt: mod.WILDLIFE_CACHE_BUILT_AT };
}

function saveCache(cache, builtAt) {
  const ts = new Date().toISOString();
  let out = `// Auto-generated by scripts/buildWildlifeCache.js — do not edit manually.\n`;
  out += `// Built: ${builtAt}\n`;
  out += `// Audit fixes applied: ${ts}\n`;
  out += `// Parks: ${Object.keys(cache).length} | Species bundled: ${Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0)}\n\n`;
  out += `export const WILDLIFE_CACHE_BUILT_AT = "${builtAt}";\n\n`;
  out += `export const WILDLIFE_CACHE = ${JSON.stringify(cache, null, 2)};\n\nexport default WILDLIFE_CACHE;\n`;
  fs.writeFileSync(path.join(ROOT, 'src', 'data', 'wildlifeCache.js'), out, 'utf8');
}

// ── HTTP helper ────────────────────────────────────────────────────────────
function fetchJson(url, headers = {}) {
  return new Promise((resolve) => {
    const u = new URL(url);
    const req = https.request({
      hostname: u.hostname,
      path: u.pathname + u.search,
      headers: { 'User-Agent': 'WildlifeMap-AuditFix/1.0', ...headers },
    }, res => {
      let data = '';
      res.on('data', d => data += d);
      res.on('end', () => { try { resolve(JSON.parse(data)); } catch { resolve(null); } });
    });
    req.on('error', () => resolve(null));
    req.setTimeout(15000, () => { req.destroy(); resolve(null); });
    req.end();
  });
}
const sleep = ms => new Promise(r => setTimeout(r, ms));

// ── fetch iNat taxon for photo + description ───────────────────────────────
const taxonCache = {};
async function fetchTaxon(name, sciName) {
  const key = sciName || name;
  if (taxonCache[key]) return taxonCache[key];
  const q = sciName || name;
  const url = `https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(q)}&rank=species,subspecies&per_page=3`;
  const data = await fetchJson(url);
  await sleep(400);
  if (!data?.results?.length) { taxonCache[key] = null; return null; }
  // prefer exact sci name match, then common name match, else first result
  let taxon = data.results.find(t => t.name?.toLowerCase() === (sciName||'').toLowerCase())
    || data.results.find(t => (t.preferred_common_name||'').toLowerCase() === name.toLowerCase())
    || data.results[0];
  const result = {
    photoUrl:    taxon.default_photo?.medium_url || null,
    photoCredit: taxon.default_photo?.attribution || null,
    description: taxon.wikipedia_summary || null,
    taxonId:     taxon.id,
  };
  taxonCache[key] = result;
  return result;
}

// ── ─────────────────────────────────────────────────────────────────────────
//  DATA DEFINITIONS
// ── ─────────────────────────────────────────────────────────────────────────

// ── P1: Rarity fixes for EXISTING animals ─────────────────────────────────
const RARITY_FIXES = [
  // Zion: Desert Bighorn Sheep — 986 iNat obs → very_likely (was unlikely)
  { park: 'zion',               name: 'Desert Bighorn Sheep', rarity: 'very_likely', seasons: ['spring','summer','fall','winter'] },
  // Great Smoky Mountains: Elk — reintroduced herd of 200+ in Cataloochee (was unlikely)
  { park: 'greatsmokymountains',name: 'Elk',                rarity: 'likely',  seasons: ['spring','summer','fall','winter'] },
  // Wind Cave: Mule Deer — common throughout park (was unlikely)
  { park: 'windcave',           name: 'Mule Deer',          rarity: 'likely' },
  // Everglades: American Crocodile — 1,470 iNat obs, recovering population (was rare)
  { park: 'everglades',         name: 'American Crocodile', rarity: 'unlikely' },
];

// ── P1+P2: New animals ─────────────────────────────────────────────────────
// Each entry: { name, sciName, type, emoji, funFact, parks: [{id, rarity, seasons}] }
const NEW_ANIMALS = [

  // ── P1-1: Elk @ Grand Canyon — 2,364 iNat obs, not yet in GC cache ──────
  {
    name: 'Elk',
    sciName: 'Cervus canadensis',
    type: 'mammal',
    emoji: '🦌',
    funFact: "Elk were reintroduced to the North Rim in the 1900s and now number several hundred on the canyon's plateau forests. They're most visible at dawn and dusk near the North Rim Visitor Center, and the bugling rut in September draws dedicated wildlife watchers to both rims.",
    parks: [{ id: 'grandcanyon', rarity: 'likely', seasons: ['spring','summer','fall','winter'] }],
  },

  // ── P1-13: Hoary Marmot @ Glacier — common in alpine meadows ────────────
  {
    name: 'Hoary Marmot',
    sciName: 'Marmota caligata',
    type: 'mammal',
    emoji: '🐿️',
    funFact: "Glacier's largest hibernator, the Hoary Marmot spends 7–8 months underground in deep sleep. Look for their silver-and-black faces sunning on lichen-covered boulders near Logan Pass in summer — their sharp whistle alarm call echoes across the alpine meadows above Going-to-the-Sun Road.",
    parks: [{ id: 'glacier', rarity: 'very_likely', seasons: ['spring','summer','fall'] }],
  },

  // ── P1-2: Columbian Ground Squirrel @ Glacier ──────────────────────────
  {
    name: 'Columbian Ground Squirrel',
    sciName: 'Urocitellus columbianus',
    type: 'mammal',
    emoji: '🐿️',
    funFact: "Glacier's most reliably-spotted mammal is active for only 4–5 months before entering one of North America's longest hibernations — up to 8 months underground. They maintain elaborate multi-chambered burrow systems used for generations.",
    parks: [{ id: 'glacier', rarity: 'very_likely', seasons: ['spring','summer','fall'] }],
  },

  // ── P1-5: Common Side-blotched Lizard (most observed SW lizard) ────────
  {
    name: 'Common Side-blotched Lizard',
    sciName: 'Uta stansburiana',
    type: 'reptile',
    emoji: '🦎',
    funFact: "The most abundant lizard in the American Southwest. Males come in three throat-color morphs — orange, blue, or yellow — each using a different mating strategy, playing out an endless rock-paper-scissors game across desert canyon walls.",
    parks: [
      { id: 'arches',            rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'canyonlands',       rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'capitolreef',       rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'petrifiedforest',   rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'saguaro',           rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'joshuatree',        rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'deathvalley',       rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'whitesands',        rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'guadalupemountains',rarity: 'unlikely',    seasons: ['spring','summer','fall'] },
      { id: 'channelislands',    rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'greatbasin',        rarity: 'likely',      seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P1-5: Plateau Fence Lizard (most observed Utah/CO plateau lizard) ──
  {
    name: 'Plateau Fence Lizard',
    sciName: 'Sceloporus tristichus',
    type: 'reptile',
    emoji: '🦎',
    funFact: "Named for its habit of perching on fence posts, rock ledges, and canyon walls to assert territory. Males perform rapid push-up displays to flash their vivid blue belly patches, visible from 50 meters away in the canyon slickrock.",
    parks: [
      { id: 'arches',          rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'canyonlands',     rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'capitolreef',     rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mesaverde',       rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'petrifiedforest', rarity: 'likely',   seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P1-6: Western Fence Lizard (most observed CA lizard) ──────────────
  {
    name: 'Western Fence Lizard',
    sciName: 'Sceloporus occidentalis',
    type: 'reptile',
    emoji: '🦎',
    funFact: "Also called the 'blue-belly,' this lizard has an unexpected bonus for humans: when ticks feed on its blood, a protein in its blood kills the Lyme disease bacteria inside the tick — significantly reducing Lyme disease rates in California forests.",
    parks: [
      { id: 'yosemite',       rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'kingscanyon',    rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'sequoia',        rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'pinnacles',      rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'joshuatree',     rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic', rarity: 'unlikely',    seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P1-7: Desert Spiny Lizard @ Saguaro ───────────────────────────────
  {
    name: 'Desert Spiny Lizard',
    sciName: 'Sceloporus clarkii',
    type: 'reptile',
    emoji: '🦎',
    funFact: "The largest spiny lizard in the U.S., the Desert Spiny Lizard is practically guaranteed at Saguaro — look for it sunning on saguaro trunks and boulders in the morning. Males are brilliantly marked with blue-green patches on throat and belly.",
    parks: [
      { id: 'saguaro',  rarity: 'guaranteed', seasons: ['spring','summer','fall'] },
      { id: 'bigbend',  rarity: 'likely',     seasons: ['spring','summer','fall'] },
      { id: 'guadalupemountains', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P1-8: Western Diamond-backed Rattlesnake @ Saguaro ────────────────
  {
    name: 'Western Diamond-backed Rattlesnake',
    sciName: 'Crotalus atrox',
    type: 'reptile',
    emoji: '🐍',
    funFact: "The largest rattlesnake in the Southwest, the Western Diamondback can reach 4–5 feet and is critical to Saguaro's ecosystem, controlling rodent populations. Despite their fearsome reputation, they give ample warning with their rattle and rarely strike unless cornered.",
    parks: [
      { id: 'saguaro',           rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'whitesands',        rarity: 'rare',     seasons: ['spring','summer','fall'] },
      { id: 'guadalupemountains',rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'bigbend',           rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'carlsbadcaverns',   rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── Zebra-tailed Lizard @ Saguaro (3rd most observed at Saguaro) ───────
  {
    name: 'Zebra-tailed Lizard',
    sciName: 'Callisaurus draconoides',
    type: 'reptile',
    emoji: '🦎',
    funFact: "One of the fastest lizards in the Sonoran Desert, the Zebra-tailed Lizard can sprint at 18 mph and runs bipedally (on two legs) when going full speed. When threatened, it curls its banded tail overhead to reveal the striking black-and-white pattern that gives it its name.",
    parks: [
      { id: 'saguaro',     rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'joshuatree',  rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'deathvalley', rarity: 'likely',      seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-9: Gateway Arch reptiles/amphibians ─────────────────────────────
  {
    name: 'American Toad',
    sciName: 'Anaxyrus americanus',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "The American Toad's long, musical trill is one of the first signs of spring along the Gateway Arch riverfront. Despite its warty appearance, handling a toad cannot give you warts — the bumps produce mild defensive toxins that taste bad to predators.",
    parks: [
      { id: 'gatewayarch',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mammothcave',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'shenandoah',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'newrivergorge', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Pond Slider',
    sciName: 'Trachemys scripta',
    type: 'reptile',
    emoji: '🐢',
    funFact: "The Pond Slider (Red-eared Slider) is the most widely distributed freshwater turtle in the world. Along the Mississippi at Gateway Arch, dozens bask on logs on sunny days. The red stripe behind each eye gives the familiar subspecies its name.",
    parks: [
      { id: 'gatewayarch',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'congaree',     rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'hotsprings',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'bigbend',      rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'American Bullfrog',
    sciName: 'Lithobates catesbeianus',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "North America's largest frog, the Bullfrog's deep 'jug-o-rum' call carries almost a mile across wetlands on summer nights. An aggressive apex amphibian, it will eat anything it can swallow — smaller frogs, snakes, mice, and even birds.",
    parks: [
      { id: 'gatewayarch', rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'congaree',    rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'indianadunes',rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'cuyahogavalley', rarity: 'likely',seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-9: Biscayne reptiles/amphibians ────────────────────────────────
  {
    name: 'Crested Anole',
    sciName: 'Anolis cristatellus',
    type: 'reptile',
    emoji: '🦎',
    funFact: "Originally from Puerto Rico, the Crested Anole is now one of Biscayne's most conspicuous reptiles — males flash their brilliant red dewlaps from mangrove roots and buttonwood branches all day long. The raised crest along the tail gives the species its name.",
    parks: [
      { id: 'biscayne',        rarity: 'very_likely', seasons: ['spring','summer','fall','winter'] },
      { id: 'drytortugas',     rarity: 'rare',        seasons: ['spring','summer','fall','winter'] },
    ],
  },
  {
    name: 'Southern Toad',
    sciName: 'Anaxyrus terrestris',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "The Southern Toad is identified by the prominent knobs behind its eyes and its high-pitched, 4–8 second trill. Most active after summer rains, large congregations gather around pools to breed — their choruses audible from a quarter mile away.",
    parks: [
      { id: 'biscayne',   rarity: 'likely', seasons: ['spring','summer','fall','winter'] },
      { id: 'congaree',   rarity: 'likely', seasons: ['spring','summer','fall'] },
      { id: 'hotsprings', rarity: 'likely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Florida Softshell Turtle',
    sciName: 'Apalone ferox',
    type: 'reptile',
    emoji: '🐢',
    funFact: "One of the largest freshwater turtles in North America, the Florida Softshell has a leathery, pancake-flat carapace instead of a hard shell, allowing it to bury in soft sediment and extend its long neck like a snorkel. Females can reach 24 inches.",
    parks: [
      { id: 'biscayne',   rarity: 'likely',   seasons: ['spring','summer','fall','winter'] },
      { id: 'everglades', rarity: 'likely',   seasons: ['spring','summer','fall','winter'] },
    ],
  },
  {
    name: 'Florida Cottonmouth',
    sciName: 'Agkistrodon conanti',
    type: 'reptile',
    emoji: '🐍',
    funFact: "Florida Cottonmouths are semi-aquatic pit vipers identified by the brilliant white interior of their mouth — a warning display shown when threatened. Critical predators in Biscayne's mangrove waterways, they control fish, frog, and small mammal populations.",
    parks: [
      { id: 'biscayne',   rarity: 'likely', seasons: ['spring','summer','fall','winter'] },
      { id: 'congaree',   rarity: 'likely', seasons: ['spring','summer','fall'] },
      { id: 'hotsprings', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'American Crocodile',
    sciName: 'Crocodylus acutus',
    type: 'reptile',
    emoji: '🐊',
    funFact: "Unlike the American Alligator, the American Crocodile is a saltwater species that frequents Biscayne Bay's mangrove shorelines and tidal creeks. Distinguished by a narrower snout and visible lower teeth — and one of very few crocodilians with a recovering U.S. population.",
    parks: [
      { id: 'biscayne',    rarity: 'likely',   seasons: ['spring','summer','fall','winter'] },
      { id: 'drytortugas', rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
    ],
  },

  // ── P2-9: Olympic amphibians ───────────────────────────────────────────
  {
    name: 'Pacific Chorus Frog',
    sciName: 'Pseudacris regilla',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "The Pacific Chorus Frog produces the iconic 'ribbit' sound most people associate with frogs worldwide — that Hollywood recording is always this species. Despite being under 2 inches long, their spring chorus from forest ponds carries hundreds of meters through the Hoh Rainforest.",
    parks: [
      { id: 'olympic',        rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'northcascades',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mountrainier',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'craterlake',     rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic', rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'redwood',        rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'channelislands', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Northwestern Salamander',
    sciName: 'Ambystoma gracile',
    type: 'amphibian',
    emoji: '🦎',
    funFact: "The Northwestern Salamander can stay permanently larval in cold fish-free forest ponds — some individuals never metamorphose and breed as gilled aquatic larvae, a phenomenon called neoteny. Look for adults under logs near streams in Olympic's Hoh Rainforest corridor.",
    parks: [
      { id: 'olympic',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'northcascades', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'mountrainier',  rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'redwood',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Western Toad',
    sciName: 'Anaxyrus boreas',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "Unlike most toads, the Western Toad doesn't trill — it makes a soft, chick-like peeping call that sounds nothing like a toad. Tadpole schools of thousands darken subalpine ponds in summer. The species is in steep decline across many mountain ranges due to chytrid fungus.",
    parks: [
      { id: 'olympic',        rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'northcascades',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mountrainier',   rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'glacier',        rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'craterlake',     rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'redwood',        rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'rockymountain',  rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'grandteton',     rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-9: Mount Rainier ────────────────────────────────────────────────
  {
    name: 'Cascades Frog',
    sciName: 'Rana cascadae',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "A true high-elevation specialist found only in the Cascades and Olympics, the Cascades Frog breeds in snowmelt pools at 3,000–9,000 feet — among the highest-altitude breeding amphibians in North America. Listed as a Species of Concern due to chytrid fungus outbreaks.",
    parks: [
      { id: 'mountrainier',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'northcascades', rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'olympic',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'craterlake',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-9: Redwood salamanders / frogs ─────────────────────────────────
  {
    name: 'Ensatina',
    sciName: 'Ensatina eschscholtzii',
    type: 'amphibian',
    emoji: '🦎',
    funFact: "A lungless salamander that breathes entirely through its moist skin, the Ensatina is among the most abundant vertebrates per acre on Redwood's forest floor. It's a classic 'ring species' — populations form a ring around California's Central Valley where distant ends can no longer interbreed.",
    parks: [
      { id: 'redwood',        rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'channelislands', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Northern Red-legged Frog',
    sciName: 'Rana aurora',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "California's largest native frog was the species celebrated in Mark Twain's 'The Celebrated Jumping Frog of Calaveras County.' Its striking crimson-red legs are only visible from below when it jumps. Listed as a California Species of Special Concern due to habitat loss and introduced predators.",
    parks: [
      { id: 'redwood',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'olympic',   rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'northcascades', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'California Slender Salamander',
    sciName: 'Batrachoseps attenuatus',
    type: 'amphibian',
    emoji: '🦎',
    funFact: "So pencil-thin it can coil like a snake when threatened, the California Slender Salamander breathes entirely through its skin. One of the most abundant vertebrates per acre in Redwood's floor litter — turn over a moist log after rain and you'll often find one curled beneath.",
    parks: [
      { id: 'redwood',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'pinnacles', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-11: Box turtles ─────────────────────────────────────────────────
  {
    name: 'Three-toed Box Turtle',
    sciName: 'Terrapene carolina triunguis',
    type: 'reptile',
    emoji: '🐢',
    funFact: "Unlike most turtles, the box turtle can completely seal itself inside its hinged shell — leaving no soft tissue exposed. They live 20–50 years in the wild and are remarkably faithful to home territories of just a few acres, sometimes spending an entire lifetime in one meadow.",
    parks: [
      { id: 'hotsprings',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'gatewayarch',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'bigbend',      rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Common Box Turtle',
    sciName: 'Terrapene carolina',
    type: 'reptile',
    emoji: '🐢',
    funFact: "The Eastern Box Turtle can seal itself completely inside its hinged shell, and may live 40–100 years — some wild individuals tracked by researchers were alive before the American Revolution. Studies show individuals using the same woodland territory for decades without wandering more than a quarter mile.",
    parks: [
      { id: 'congaree',      rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'mammothcave',   rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'newrivergorge', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'indianadunes',  rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'shenandoah',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'cuyahogavalley',rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },

  // ── P2-12: Green Sea Turtle ────────────────────────────────────────────
  {
    name: 'Green Sea Turtle',
    sciName: 'Chelonia mydas',
    type: 'reptile',
    emoji: '🐢',
    funFact: "The only adult herbivore among sea turtles, the Green Sea Turtle grazes on seagrass beds like an aquatic cow — its diet of sea grasses and algae turns its fat green, giving the species its name. Females navigate thousands of miles to return to the exact beach where they hatched.",
    parks: [
      { id: 'virginislands', rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
      { id: 'drytortugas',   rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
      { id: 'haleakala',     rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
      { id: 'biscayne',      rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
      { id: 'americansamoa', rarity: 'unlikely', seasons: ['spring','summer','fall','winter'] },
    ],
  },

  // ── Additional high-value animals found in audit ───────────────────────
  {
    name: 'Common Chuckwalla',
    sciName: 'Sauromalus ater',
    type: 'reptile',
    emoji: '🦎',
    funFact: "The Chuckwalla is North America's second-largest lizard, reaching 16 inches. When threatened, it squeezes into a rock crevice and inflates its body to become nearly impossible to extract. Adult males at Joshua Tree are jet black with orange or red patches — unmistakable on open rock faces.",
    parks: [
      { id: 'joshuatree',  rarity: 'very_likely', seasons: ['spring','summer','fall'] },
      { id: 'deathvalley', rarity: 'likely',      seasons: ['spring','summer','fall'] },
      { id: 'saguaro',     rarity: 'unlikely',    seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Gopher Snake',
    sciName: 'Pituophis catenifer',
    type: 'reptile',
    emoji: '🐍',
    funFact: "The Gopher Snake is a master mimic — when threatened, it flattens its head into a triangular shape, vibrates its tail, and hisses loudly to impersonate a rattlesnake. Despite the act, it's a non-venomous constrictor and an important rodent predator across western parks.",
    parks: [
      { id: 'arches',            rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'canyonlands',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'capitolreef',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'petrifiedforest',   rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mesaverde',         rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'joshuatree',        rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'pinnacles',         rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'sequoia',           rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'channelislands',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'guadalupemountains',rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Western Terrestrial Garter Snake',
    sciName: 'Thamnophis elegans',
    type: 'reptile',
    emoji: '🐍',
    funFact: "One of the most widely distributed snakes in the Rocky Mountains, the Western Terrestrial Garter Snake is active from snowmelt through early autumn. Unlike most garter snakes, some populations have evolved resistance to the toxic newts they eat, accumulating the toxin harmlessly in their own bodies.",
    parks: [
      { id: 'grandteton',     rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'rockymountain',  rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'glacier',        rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'craterlake',     rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'lassenvolcanic', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'yosemite',       rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'kingscanyon',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Columbia Spotted Frog',
    sciName: 'Rana luteiventris',
    type: 'amphibian',
    emoji: '🐸',
    funFact: "One of the earliest-breeding amphibians in the Rockies, the Columbia Spotted Frog lays eggs in ponds still partially frozen in late winter. Adults spend summer near water, diving in with a 'plop' when disturbed — a sound commonly heard along Teton and Glacier alpine ponds.",
    parks: [
      { id: 'grandteton', rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'glacier',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Western Tiger Salamander',
    sciName: 'Ambystoma mavortium',
    type: 'amphibian',
    emoji: '🦎',
    funFact: "North America's largest land-dwelling salamander, the Western Tiger Salamander emerges from burrows during rain to breed in prairie ponds — often the same ponds each year. Adults spend most of their lives underground, only appearing above ground on rainy nights.",
    parks: [
      { id: 'rockymountain', rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'grandteton',    rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'badlands',      rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Rough-skinned Newt',
    sciName: 'Taricha granulosa',
    type: 'amphibian',
    emoji: '🦎',
    funFact: "The Rough-skinned Newt carries tetrodotoxin — the same lethal toxin found in puffer fish — making it one of the most toxic amphibians in North America. Garter snakes in the Pacific Northwest have co-evolved resistance to the toxin in an arms-race between predator and prey.",
    parks: [
      { id: 'olympic',      rarity: 'unlikely', seasons: ['spring','summer','fall'] },
      { id: 'redwood',      rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'northcascades',rarity: 'unlikely', seasons: ['spring','summer','fall'] },
    ],
  },
  {
    name: 'Hawksbill Sea Turtle',
    sciName: 'Eretmochelys imbricata',
    type: 'reptile',
    emoji: '🐢',
    funFact: "The Hawksbill Sea Turtle is the only sea turtle that regularly feeds on sponges — an animal most other creatures cannot eat due to toxic chemicals. Their narrow, pointed beak lets them reach into coral crevices. Critically endangered, every sighting in the Virgin Islands is a conservation milestone.",
    parks: [
      { id: 'virginislands', rarity: 'rare',     seasons: ['spring','summer','fall','winter'] },
      { id: 'drytortugas',   rarity: 'rare',     seasons: ['spring','summer','fall','winter'] },
      { id: 'biscayne',      rarity: 'rare',     seasons: ['spring','summer','fall','winter'] },
    ],
  },
  {
    name: 'Eastern Collared Lizard',
    sciName: 'Crotaphytus collaris',
    type: 'reptile',
    emoji: '🦎',
    funFact: "The Eastern Collared Lizard is one of the most visually striking reptiles of the Southwest — males display vivid turquoise, yellow, and orange scales with a distinctive black-and-white collar. When running at full speed, they raise their front legs and sprint bipedally on their hind legs.",
    parks: [
      { id: 'petrifiedforest', rarity: 'likely',   seasons: ['spring','summer','fall'] },
      { id: 'mesaverde',       rarity: 'likely',   seasons: ['spring','summer','fall'] },
    ],
  },
];

// ── ─────────────────────────────────────────────────────────────────────────
//  MAIN
// ── ─────────────────────────────────────────────────────────────────────────
async function main() {
  console.log('══════════════════════════════════════════════════');
  console.log('  Applying Priority 1 + 2 Audit Fixes');
  console.log('══════════════════════════════════════════════════\n');

  const { cache, builtAt } = loadCache();

  let rarityFixed = 0;
  let animalsAdded = 0;
  const addedList = [];

  // ── Step 1: Apply rarity fixes to existing animals ─────────────────────
  console.log('Step 1 — Applying rarity/season fixes to existing animals…');
  for (const fix of RARITY_FIXES) {
    const park = cache[fix.park];
    if (!park?.animals) { console.log(`  ⚠ Park not found: ${fix.park}`); continue; }
    const animal = park.animals.find(a => a.name.toLowerCase() === fix.name.toLowerCase());
    if (!animal) { console.log(`  ⚠ Animal not found: ${fix.name} @ ${fix.park}`); continue; }
    const old = animal.rarity;
    animal.rarity = fix.rarity;
    if (fix.seasons) animal.seasons = fix.seasons;
    console.log(`  ✓ ${fix.name} @ ${fix.park}: ${old} → ${fix.rarity}${fix.seasons ? ' seasons='+fix.seasons.join(',') : ''}`);
    rarityFixed++;
  }

  // ── Step 2: Prefetch iNat taxon data for all unique new species ────────
  console.log('\nStep 2 — Fetching iNat taxon data (photos + descriptions)…');
  const uniqueSpecies = [...new Set(NEW_ANIMALS.map(a => a.sciName || a.name))];
  const taxonMap = {};
  for (const sp of uniqueSpecies) {
    const animalDef = NEW_ANIMALS.find(a => (a.sciName || a.name) === sp);
    process.stdout.write(`  ${animalDef?.name || sp}… `);
    const t = await fetchTaxon(animalDef?.name || sp, sp);
    if (t) {
      taxonMap[sp] = t;
      console.log(`✓ photo=${!!t.photoUrl} desc=${t.description?.length || 0}chars`);
    } else {
      console.log('⚠ no taxon data');
    }
  }

  // ── Step 3: Add new animals to parks ──────────────────────────────────
  console.log('\nStep 3 — Adding new animals to parks…');
  for (const animalDef of NEW_ANIMALS) {
    const taxon = taxonMap[animalDef.sciName || animalDef.name];
    // Use Wikipedia description if available, else use funFact as fallback description
    const description = taxon?.description || animalDef.funFact;

    for (const parkEntry of animalDef.parks) {
      const park = cache[parkEntry.id];
      if (!park) { console.log(`  ⚠ Park not found: ${parkEntry.id}`); continue; }
      // Check not already present
      const exists = park.animals.some(a => a.name.toLowerCase() === animalDef.name.toLowerCase());
      if (exists) {
        // Update rarity/seasons if exists (e.g. American Crocodile @ Biscayne we add separately)
        const existing = park.animals.find(a => a.name.toLowerCase() === animalDef.name.toLowerCase());
        if (existing && parkEntry.rarity !== existing.rarity) {
          const old = existing.rarity;
          existing.rarity = parkEntry.rarity;
          existing.seasons = parkEntry.seasons;
          console.log(`  ↑ updated ${animalDef.name} @ ${parkEntry.id}: ${old} → ${parkEntry.rarity}`);
        }
        continue;
      }

      const newAnimal = {
        name:           animalDef.name,
        emoji:          animalDef.emoji,
        animalType:     animalDef.type,
        rarity:         parkEntry.rarity,
        seasons:        parkEntry.seasons,
        scientificName: animalDef.sciName || null,
        funFact:        animalDef.funFact,
        photoUrl:       taxon?.photoUrl || null,
        source:         'inaturalist',
        sources:        ['inaturalist'],
        description:    description,
        descriptionSource: taxon?.description ? 'Wikipedia' : 'Park Records',
      };

      park.animals.push(newAnimal);
      animalsAdded++;
      addedList.push(`${animalDef.name} @ ${parkEntry.id} (${parkEntry.rarity})`);
      console.log(`  + ${animalDef.name} @ ${parkEntry.id} [${parkEntry.rarity}]`);
    }
  }

  // ── Step 4: Save cache ─────────────────────────────────────────────────
  console.log('\nStep 4 — Writing updated wildlifeCache.js…');
  saveCache(cache, builtAt);
  const totalAnimals = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0);
  console.log(`  ✓ Written: ${totalAnimals} total animals (was 28,601)`);

  // ── Summary ────────────────────────────────────────────────────────────
  console.log('\n══════════════════════════════════════════════════');
  console.log(`  Rarity fixes applied: ${rarityFixed}`);
  console.log(`  New animals added:    ${animalsAdded}`);
  console.log(`  Total animals now:    ${totalAnimals}`);
  console.log('══════════════════════════════════════════════════');
  console.log('\nAdded:');
  addedList.forEach(a => console.log('  ' + a));
}

main().catch(err => { console.error('Fix script failed:', err); process.exit(1); });
