'use strict';
/**
 * applyMammalFixes.cjs — Comprehensive mammal audit fixes
 *
 * Sections:
 *  1. Add 19+ genuinely missing mammals
 *  2. Fix over-stated rarities (downgrades)
 *  3. Fix under-stated rarities (upgrades)
 *  4. Fix seasonal inaccuracies (bears + ground squirrels — remove winter)
 *  5. Fix cross-park consistency issues
 *  6. Add missing marine mammals
 *
 * Run: node scripts/applyMammalFixes.cjs
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const ROOT       = path.join(__dirname, '..');
const CACHE_PATH = path.join(ROOT, 'src', 'data', 'wildlifeCache.js');

// ── Load cache ─────────────────────────────────────────────────────────────────
function loadCache() {
  const src = fs.readFileSync(CACHE_PATH, 'utf8');
  const cjs = src
    .replace('export const WILDLIFE_CACHE_BUILT_AT', 'const WILDLIFE_CACHE_BUILT_AT')
    .replace('export const WILDLIFE_CACHE', 'const WILDLIFE_CACHE')
    .replace('export default WILDLIFE_CACHE;', '')
    + '\nmodule.exports = { WILDLIFE_CACHE, WILDLIFE_CACHE_BUILT_AT };';
  const tmp = path.join(os.tmpdir(), '_mamfix_tmp.cjs');
  fs.writeFileSync(tmp, cjs);
  delete require.cache[require.resolve(tmp)];
  const mod = require(tmp);
  fs.unlinkSync(tmp);
  return { cache: mod.WILDLIFE_CACHE, builtAt: mod.WILDLIFE_CACHE_BUILT_AT };
}

// ── Save cache ─────────────────────────────────────────────────────────────────
function saveCache(cache, builtAt) {
  const ts = new Date().toISOString();
  let out = `// Auto-generated by scripts/buildWildlifeCache.js — do not edit manually.\n`;
  out += `// Built: ${builtAt}\n`;
  out += `// Mammal audit fixes applied: ${ts}\n`;
  out += `// Parks: ${Object.keys(cache).length} | Species bundled: ${Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0)}\n\n`;
  out += `export const WILDLIFE_CACHE_BUILT_AT = "${builtAt}";\n\n`;
  out += `export const WILDLIFE_CACHE = ${JSON.stringify(cache, null, 2)};\n\nexport default WILDLIFE_CACHE;\n`;
  fs.writeFileSync(CACHE_PATH, out, 'utf8');
}

// ── Helper: find animal by name (case-insensitive, partial match) ─────────────
function findAnimal(animals, name) {
  const n = name.toLowerCase().trim();
  return animals.find(a => {
    const an = (a.name || '').toLowerCase().trim();
    return an === n || an.includes(n) || n.includes(an);
  });
}

// ── Helper: add animal if not already present ─────────────────────────────────
function addIfMissing(animals, animal, stats) {
  const existing = findAnimal(animals, animal.name);
  if (existing) {
    stats.skipped++;
    return false;
  }
  animals.push(animal);
  stats.added++;
  return true;
}

// ── Helper: fix rarity of existing animal ────────────────────────────────────
function fixRarity(animals, name, newRarity, stats) {
  const a = findAnimal(animals, name);
  if (!a) {
    stats.notFound++;
    return false;
  }
  if (a.rarity === newRarity) return false;
  const old = a.rarity;
  a.rarity = newRarity;
  stats.rarityFixed++;
  stats.rarityLog.push(`  ${a.name}: ${old} → ${newRarity}`);
  return true;
}

// ── Helper: remove season from existing animal ────────────────────────────────
function removeSeason(animals, namePredicate, seasonToRemove, stats) {
  let count = 0;
  for (const a of animals) {
    if (!namePredicate(a.name)) continue;
    if (!a.seasons?.includes(seasonToRemove)) continue;
    a.seasons = a.seasons.filter(s => s !== seasonToRemove);
    stats.seasonFixed++;
    stats.seasonLog.push(`  ${a.name}: removed ${seasonToRemove}`);
    count++;
  }
  return count;
}

// ── Animal template builder ────────────────────────────────────────────────────
function mammal(name, sciName, emoji, rarity, seasons, obsCount, photoUrl = null) {
  return {
    name,
    emoji,
    animalType: 'mammal',
    rarity,
    seasons,
    scientificName: sciName,
    funFact: `${obsCount} research-grade iNaturalist observations at this park.`,
    photoUrl,
    source: 'inaturalist',
    sources: ['inaturalist'],
    description: null,
    descriptionSource: null,
  };
}

function marineMammal(name, sciName, emoji, rarity, seasons, obsCount, photoUrl = null) {
  return {
    name,
    emoji,
    animalType: 'marine',
    rarity,
    seasons,
    scientificName: sciName,
    funFact: `${obsCount} research-grade iNaturalist observations at this park.`,
    photoUrl,
    source: 'inaturalist',
    sources: ['inaturalist'],
    description: null,
    descriptionSource: null,
  };
}

const ALL_SEASONS  = ['spring','summer','fall','winter'];
const ACTIVE_SEASONS = ['spring','summer','fall'];  // for hibernating species

// ════════════════════════════════════════════════════════════════════════════════
// DATA
// ════════════════════════════════════════════════════════════════════════════════

// Section 1 + 5 + 6: New animals to add {park: [...animals]}
const NEW_ANIMALS = {

  // ── GLACIER (12 from S1 + 3 from S5) ───────────────────────────────────────
  glacier: [
    mammal('Mule Deer',                          'Odocoileus hemionus',        '🦌', 'likely',   ALL_SEASONS,    450),
    mammal('White-tailed Deer',                  'Odocoileus virginianus',     '🦌', 'likely',   ALL_SEASONS,    309),
    mammal('Common Golden-mantled Ground Squirrel','Callospermophilus lateralis','🐿️','likely',  ACTIVE_SEASONS, 574),
    mammal('American Red Squirrel',              'Tamiasciurus hudsonicus',    '🐿️', 'likely',   ALL_SEASONS,    200),
    mammal('Red Fox',                            'Vulpes vulpes',              '🦊', 'unlikely', ALL_SEASONS,    76),
    mammal('Snowshoe Hare',                      'Lepus americanus',           '🐇', 'unlikely', ALL_SEASONS,    70),
    mammal('American Beaver',                    'Castor canadensis',          '🦫', 'unlikely', ALL_SEASONS,    53),
    mammal('Yellow-pine Chipmunk',               'Neotamias amoenus',          '🐿️', 'unlikely', ACTIVE_SEASONS, 41),
    mammal('Red-tailed Chipmunk',                'Neotamias ruficaudus',       '🐿️', 'unlikely', ACTIVE_SEASONS, 27),
    mammal('Yellow-bellied Marmot',              'Marmota flaviventris',       '🐿️', 'unlikely', ACTIVE_SEASONS, 24),
    mammal('American Marten',                    'Martes americana',           '🦡', 'unlikely', ALL_SEASONS,    21),
    mammal('Long-tailed Weasel',                 'Neogale frenata',            '🐾', 'unlikely', ALL_SEASONS,    20),
    mammal('Elk',                                'Cervus canadensis',          '🦌', 'unlikely', ALL_SEASONS,    36),
    mammal('Coyote',                             'Canis latrans',              '🐺', 'unlikely', ALL_SEASONS,    30),
    mammal('Striped Skunk',                      'Mephitis mephitis',          '🦨', 'rare',     ALL_SEASONS,    15),
  ],

  // ── DENALI ──────────────────────────────────────────────────────────────────
  denali: [
    mammal('Grizzly Bear',  'Ursus arctos horribilis', '🐻', 'unlikely', ACTIVE_SEASONS, 120),
    mammal('Dall Sheep',    'Ovis dalli',              '🐑', 'likely',   ALL_SEASONS,    429),
  ],

  // ── CONGAREE ────────────────────────────────────────────────────────────────
  congaree: [
    mammal('Wild Boar',    'Sus scrofa',              '🐗', 'likely',   ALL_SEASONS,    141),
    mammal('Black Bear',   'Ursus americanus',        '🐻', 'unlikely', ACTIVE_SEASONS, 80),
    mammal('Raccoon',      'Procyon lotor',           '🦝', 'unlikely', ALL_SEASONS,    40),
  ],

  // ── GREAT SMOKY MOUNTAINS ───────────────────────────────────────────────────
  greatsmokymountains: [
    mammal('Wild Boar', 'Sus scrofa', '🐗', 'unlikely', ALL_SEASONS, 35),
  ],

  // ── HAWAII VOLCANOES ────────────────────────────────────────────────────────
  hawaiivolcanoes: [
    mammal('Wild Boar', 'Sus scrofa', '🐗', 'unlikely', ALL_SEASONS, 32),
  ],

  // ── SAGUARO ─────────────────────────────────────────────────────────────────
  saguaro: [
    mammal('Javelina', 'Pecari tajacu', '🐗', 'likely', ALL_SEASONS, 380),
  ],

  // ── MAMMOTH CAVE ────────────────────────────────────────────────────────────
  mammothcave: [
    mammal('Raccoon',        'Procyon lotor',       '🦝', 'unlikely', ALL_SEASONS,    40),
    mammal('Virginia Opossum','Didelphis virginiana','🐾', 'unlikely', ALL_SEASONS,    20),
  ],

  // ── HOT SPRINGS ─────────────────────────────────────────────────────────────
  hotsprings: [
    mammal('Virginia Opossum', 'Didelphis virginiana', '🐾', 'unlikely', ALL_SEASONS, 15),
  ],

  // ── YOSEMITE ────────────────────────────────────────────────────────────────
  yosemite: [
    mammal('Striped Skunk', 'Mephitis mephitis', '🦨', 'rare', ALL_SEASONS, 30),
  ],

  // ── GRAND CANYON ────────────────────────────────────────────────────────────
  grandcanyon: [
    mammal('Striped Skunk', 'Mephitis mephitis', '🦨', 'rare', ALL_SEASONS, 20),
  ],

  // ── VOYAGEURS ───────────────────────────────────────────────────────────────
  voyageurs: [
    mammal('Moose', 'Alces alces', '🫎', 'likely', ALL_SEASONS, 120),
  ],

  // ── OLYMPIC ─────────────────────────────────────────────────────────────────
  olympic: [
    mammal('Moose',         'Alces alces',             '🫎', 'unlikely', ALL_SEASONS, 50),
    mammal('Red Squirrel',  'Tamiasciurus hudsonicus', '🐿️','unlikely', ALL_SEASONS,  40),
    marineMammal('Grey Whale',       'Eschrichtius robustus',  '🐋', 'rare',     ['spring','fall'], 25),
    marineMammal('Harbour Porpoise', 'Phocoena phocoena',      '🐬', 'exceptional', ALL_SEASONS,   6),
  ],

  // ── CHANNEL ISLANDS ─────────────────────────────────────────────────────────
  channelislands: [
    marineMammal('Grey Whale',  'Eschrichtius robustus', '🐋', 'rare', ['spring','fall'], 28),
    marineMammal('Sea Otter',   'Enhydra lutris',        '🦦', 'unlikely', ALL_SEASONS,   50),
  ],

  // ── ACADIA ──────────────────────────────────────────────────────────────────
  acadia: [
    marineMammal('Grey Seal',        'Halichoerus grypus', '🦭', 'unlikely',   ALL_SEASONS, 26),
    marineMammal('Harbour Porpoise', 'Phocoena phocoena',  '🐬', 'exceptional', ALL_SEASONS, 8),
    marineMammal('Humpback Whale',   'Megaptera novaeangliae','🐋','unlikely', ['spring','summer','fall'], 20),
  ],

  // ── GLACIER BAY ─────────────────────────────────────────────────────────────
  glacierbay: [
    marineMammal('Harbour Porpoise', 'Phocoena phocoena', '🐬', 'exceptional', ALL_SEASONS, 14),
  ],

  // ── KENAI FJORDS ────────────────────────────────────────────────────────────
  kenaifjords: [
    marineMammal('California Sea Lion', 'Zalophus californianus', '🦭', 'likely', ['spring','summer','fall'], 30),
  ],

  // ── EVERGLADES ──────────────────────────────────────────────────────────────
  everglades: [
    marineMammal('Florida Manatee', 'Trichechus manatus latirostris', '🐋', 'unlikely', ALL_SEASONS, 350),
  ],

  // ── BISCAYNE ────────────────────────────────────────────────────────────────
  biscayne: [
    marineMammal('Florida Manatee', 'Trichechus manatus latirostris', '🐋', 'unlikely', ALL_SEASONS, 100),
  ],
};

// Section 2: Rarity downgrades — cache too HIGH
const RARITY_DOWNGRADES = [
  { park: 'hotsprings',       name: 'Eastern Gray Squirrel',    newRarity: 'unlikely' },
  { park: 'hotsprings',       name: 'White-tailed Deer',        newRarity: 'unlikely' },
  { park: 'kenaifjords',      name: 'Sea Otter',                newRarity: 'likely' },
  { park: 'kenaifjords',      name: 'Harbor Seal',              newRarity: 'likely' },
  { park: 'kenaifjords',      name: 'Humpback Whale',           newRarity: 'unlikely' },
  { park: 'lakeclark',        name: 'Brown Bear',               newRarity: 'unlikely' },
  { park: 'mesaverde',        name: 'Mule Deer',                newRarity: 'unlikely' },
  { park: 'indianadunes',     name: 'White-tailed Deer',        newRarity: 'unlikely' },
  { park: 'newrivergorge',    name: 'White-tailed Deer',        newRarity: 'unlikely' },
  { park: 'gatewayarch',      name: 'Eastern Gray Squirrel',    newRarity: 'unlikely' },
  { park: 'congaree',         name: 'White-tailed Deer',        newRarity: 'unlikely' },
  { park: 'theodoreroosevelt',name: 'American Bison',           newRarity: 'very_likely' },
  { park: 'badlands',         name: 'American Bison',           newRarity: 'very_likely' },
  { park: 'badlands',         name: 'Pronghorn',                newRarity: 'very_likely' },
  { park: 'windcave',         name: 'American Bison',           newRarity: 'very_likely' },
  { park: 'grandteton',       name: 'American Bison',           newRarity: 'very_likely' },
  { park: 'glacierbay',       name: 'Humpback Whale',           newRarity: 'unlikely' },
  { park: 'glacier',          name: 'Mountain Goat',            newRarity: 'unlikely' },
  { park: 'denali',           name: 'Moose',                    newRarity: 'unlikely' },
  { park: 'greatsmokymountains', name: 'Black Bear',            newRarity: 'unlikely' },
  { park: 'yellowstone',      name: 'Elk',                      newRarity: 'very_likely' },
];

// Section 3: Rarity upgrades — cache too LOW
const RARITY_UPGRADES = [
  { park: 'rockymountain',    name: 'Moose',          newRarity: 'very_likely' },
  { park: 'rockymountain',    name: 'American Pika',  newRarity: 'very_likely' },
  { park: 'everglades',       name: 'West Indian Manatee', newRarity: 'very_likely' },
  { park: 'everglades',       name: 'Florida Manatee',     newRarity: 'very_likely' },
  { park: 'yellowstone',      name: 'Gray Wolf',      newRarity: 'unlikely' },
  { park: 'grandcanyon',      name: 'American Bison', newRarity: 'unlikely' },
];

// Section 4: Seasonal fixes
// Parks where bears should NOT have winter
const BEAR_NO_WINTER_PARKS = [
  'everglades', 'newrivergorge', 'grandcanyon', 'zion', 'capitolreef',
  'bigbend', 'gatesofthearctic', 'hotsprings',
];

// Parks where ground squirrels/marmots should NOT have winter
const SQUIRREL_NO_WINTER_PARKS = [
  'windcave', 'theodoreroosevelt', 'zion', 'brycecanyon', 'arches',
  'greatsanddunes', 'olympic', 'northcascades', 'craterlake', 'lassenvolcanic',
  'joshuatree', 'deathvalley', 'lakeclark',
];

// Name patterns for each hibernating group
function isBearName(name) {
  return /\b(black bear|american black bear|brown bear|grizzly bear|bear)\b/i.test(name);
}
function isHibernatingSquirrel(name) {
  return /\b(ground squirrel|marmot|prairie dog|groundhog|woodchuck)\b/i.test(name);
}

// Section 5: Cross-park rarity fixes for existing animals
const CROSS_PARK_RARITY = [
  // White-tailed Deer upgrades
  { park: 'voyageurs',         name: 'White-tailed Deer',  newRarity: 'likely' },
  { park: 'badlands',          name: 'White-tailed Deer',  newRarity: 'likely' },
  { park: 'windcave',          name: 'White-tailed Deer',  newRarity: 'likely' },
  { park: 'theodoreroosevelt', name: 'White-tailed Deer',  newRarity: 'likely' },
  // Virginia Opossum upgrades
  { park: 'shenandoah',        name: 'Virginia Opossum',   newRarity: 'unlikely' },
  { park: 'greatsmokymountains',name: 'Virginia Opossum',  newRarity: 'unlikely' },
  { park: 'congaree',          name: 'Virginia Opossum',   newRarity: 'unlikely' },
  { park: 'mammothcave',       name: 'Virginia Opossum',   newRarity: 'unlikely' },
  // Eastern Gray Squirrel upgrades
  { park: 'acadia',            name: 'Eastern Gray Squirrel', newRarity: 'likely' },
  { park: 'newrivergorge',     name: 'Eastern Gray Squirrel', newRarity: 'likely' },
  { park: 'shenandoah',        name: 'Eastern Gray Squirrel', newRarity: 'likely' },
  // Raccoon upgrades
  { park: 'shenandoah',        name: 'Raccoon',    newRarity: 'unlikely' },
  { park: 'greatsmokymountains',name: 'Raccoon',   newRarity: 'unlikely' },
  { park: 'acadia',            name: 'Raccoon',    newRarity: 'unlikely' },
  { park: 'hotsprings',        name: 'Raccoon',    newRarity: 'unlikely' },
  { park: 'newrivergorge',     name: 'Raccoon',    newRarity: 'unlikely' },
  // American Beaver upgrades
  { park: 'rockymountain',     name: 'American Beaver',   newRarity: 'unlikely' },
  { park: 'voyageurs',         name: 'American Beaver',   newRarity: 'unlikely' },
  { park: 'shenandoah',        name: 'American Beaver',   newRarity: 'unlikely' },
  // Moose upgrades
  { park: 'northcascades',     name: 'Moose',  newRarity: 'unlikely' },
];

// ════════════════════════════════════════════════════════════════════════════════
// MAIN
// ════════════════════════════════════════════════════════════════════════════════
function main() {
  console.log('══════════════════════════════════════════════════════════════');
  console.log('  Comprehensive Mammal Fixes');
  console.log('══════════════════════════════════════════════════════════════\n');

  const { cache, builtAt } = loadCache();
  const before = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length, 0);

  const stats = {
    added:       0,
    skipped:     0,
    notFound:    0,
    rarityFixed: 0,
    seasonFixed: 0,
    rarityLog:   [],
    seasonLog:   [],
  };

  // ── Section 1+5+6: Add new animals ────────────────────────────────────────
  console.log('── Section 1/5/6: Adding missing animals ─────────────────────');
  for (const [parkId, animals] of Object.entries(NEW_ANIMALS)) {
    if (!cache[parkId]) { console.log(`  ⚠  Park not found: ${parkId}`); continue; }
    const parkAnimals = cache[parkId].animals;
    const parkAdded = [];
    for (const animal of animals) {
      const added = addIfMissing(parkAnimals, animal, stats);
      if (added) parkAdded.push(`${animal.name} (${animal.rarity})`);
    }
    if (parkAdded.length) {
      console.log(`  [${parkId}] +${parkAdded.length}: ${parkAdded.join(', ')}`);
    }
  }

  // ── Section 2: Rarity downgrades ─────────────────────────────────────────
  console.log('\n── Section 2: Downgrades ─────────────────────────────────────');
  for (const fix of RARITY_DOWNGRADES) {
    if (!cache[fix.park]) continue;
    fixRarity(cache[fix.park].animals, fix.name, fix.newRarity, stats);
  }
  stats.rarityLog.slice(0, 30).forEach(l => console.log(l));

  // ── Section 3: Rarity upgrades ────────────────────────────────────────────
  console.log('\n── Section 3: Upgrades ───────────────────────────────────────');
  const upgradeLogStart = stats.rarityLog.length;
  for (const fix of RARITY_UPGRADES) {
    if (!cache[fix.park]) continue;
    fixRarity(cache[fix.park].animals, fix.name, fix.newRarity, stats);
  }
  stats.rarityLog.slice(upgradeLogStart).forEach(l => console.log(l));

  // ── Section 4: Seasonal fixes ─────────────────────────────────────────────
  console.log('\n── Section 4: Seasonal fixes (remove winter from hibernators) ─');
  for (const parkId of BEAR_NO_WINTER_PARKS) {
    if (!cache[parkId]) continue;
    const n = removeSeason(cache[parkId].animals, isBearName, 'winter', stats);
    if (n > 0) console.log(`  [${parkId}] removed winter from ${n} bear(s)`);
  }
  for (const parkId of SQUIRREL_NO_WINTER_PARKS) {
    if (!cache[parkId]) continue;
    const n = removeSeason(cache[parkId].animals, isHibernatingSquirrel, 'winter', stats);
    if (n > 0) console.log(`  [${parkId}] removed winter from ${n} ground squirrel/marmot(s)`);
  }

  // ── Section 5: Cross-park rarity fixes ────────────────────────────────────
  console.log('\n── Section 5: Cross-park rarity fixes ────────────────────────');
  const crossLogStart = stats.rarityLog.length;
  for (const fix of CROSS_PARK_RARITY) {
    if (!cache[fix.park]) continue;
    fixRarity(cache[fix.park].animals, fix.name, fix.newRarity, stats);
  }
  stats.rarityLog.slice(crossLogStart).forEach(l => console.log(l));

  // ── Summary ───────────────────────────────────────────────────────────────
  const after = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length, 0);
  console.log('\n══════════════════════════════════════════════════════════════');
  console.log(`  Animals added:         ${stats.added} (${before} → ${after})`);
  console.log(`  Rarity corrections:    ${stats.rarityFixed}`);
  console.log(`  Seasonal fixes:        ${stats.seasonFixed}`);
  console.log(`  Skipped (duplicates):  ${stats.skipped}`);
  console.log(`  Not found in cache:    ${stats.notFound}`);
  console.log('══════════════════════════════════════════════════════════════\n');

  saveCache(cache, builtAt);
  console.log(`✓ Written: ${after} total animals`);
}

main();
