#!/usr/bin/env node
/**
 * scripts/buildSpeciesSearchIndex.mjs — species the search could not offer.
 *
 *   node scripts/buildSpeciesSearchIndex.mjs
 *
 * WHY: the search suggestion list is built from WILDLIFE_CACHE — the 63
 * national parks — which is 2,583 species. The county datasets hold 8,377
 * non-bird and 967 bird species, so ~7,000 animals the app HAS data for could
 * not be searched at all: Brown Bear, Caribou, Walrus, Grey Whale. Since the
 * search requires picking a suggestion, they were unreachable.
 *
 * This emits the DIFFERENCE (county species not already in the cache) so the
 * suggestion list can be topped up without duplicating what's already there.
 *
 * parkCount is a real count — state parks whose county records the species —
 * so it means the same thing as the cache's parkCount and sorts sensibly.
 *
 * Committed like npsUnits.js rather than generated during `npm run build`,
 * because src/ imports it and it only changes when the county data does.
 * Re-run after a county bird/non-bird rebuild.
 */
import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { WILDLIFE_CACHE } from '../src/data/wildlifeCacheLoader.js';
import { PARK_COUNTY, COUNTY_BIRD_FREQ } from '../src/data/stateParkBirdFreq.js';
import { loadCountyNonbird, NONBIRD_STATE_KEYS } from '../src/data/countyNonbird/loader.js';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'data', 'speciesSearchIndex.js');

// Names the suggestion list already offers — skip these entirely.
const known = new Set();
for (const d of Object.values(WILDLIFE_CACHE))
  for (const a of d.animals ?? []) if (a.name) known.add(a.name.toLowerCase());

// county → how many state parks sit in it (parkCount denominator)
const parksPerCounty = {};
for (const c of Object.values(PARK_COUNTY)) parksPerCounty[c] = (parksPerCounty[c] ?? 0) + 1;

/** name(lowercase) → { g: group, p: park count } */
const found = new Map();
const add = (name, group, county) => {
  const key = String(name).toLowerCase();
  if (!key || known.has(key)) return;
  const rec = found.get(key) ?? { g: group, p: 0 };
  rec.p += parksPerCounty[county] ?? 0;
  found.set(key, rec);
};

for (const [county, spp] of Object.entries(COUNTY_BIRD_FREQ))
  for (const sp of Object.keys(spp)) { if (!sp.startsWith('__')) add(sp, 'bird', county); }

for (const key of NONBIRD_STATE_KEYS) {
  const mod = await loadCountyNonbird(key);
  if (!mod) continue;
  for (const [county, groups] of Object.entries(mod))
    for (const [group, list] of Object.entries(groups)) {
      if (!Array.isArray(list)) continue;
      for (const pair of list) if (pair?.[0]) add(pair[0], group, county);
    }
}

// Title Case for display; capitalise after whitespace only, so "Red-tailed
// Hawk" and "White-tailed Deer" keep their lowercase second element.
const titleCase = n => String(n).replace(/(^|\s)\S/g, c => c.toUpperCase());

// Drop species with no state park to send anyone to. Their counties hold
// refuges or NPS units but no state park, and findStateParksWithSpecies only
// returns state parks — so suggesting them produces a dead end (Walrus offered
// "0 parks" and an empty result). 558 of 7,036 entries.
const rows = [...found.entries()]
  .map(([name, r]) => [titleCase(name), r.g, r.p])
  .filter(([, , parks]) => parks > 0)
  .sort((a, b) => b[2] - a[2] || a[0].localeCompare(b[0]));

const byGroup = rows.reduce((m, r) => (m[r[1]] = (m[r[1]] ?? 0) + 1, m), {});

writeFileSync(OUT,
  `// Auto-generated by scripts/buildSpeciesSearchIndex.mjs — do not edit.\n` +
  `// ${rows.length} species present in the county datasets but NOT in\n` +
  `// WILDLIFE_CACHE, so the search suggestion list could not offer them.\n` +
  `// Shape: [displayName, animalType, parkCount]. Loaded lazily — this is\n` +
  `// only needed once someone actually types in the species search.\n` +
  `export const SPECIES_SEARCH_EXTRA = ${JSON.stringify(rows)};\n`,
  'utf8');

console.log(`✅ ${rows.length} extra searchable species → src/data/speciesSearchIndex.js`);
for (const [g, n] of Object.entries(byGroup).sort((a, b) => b[1] - a[1])) console.log(`   ${g}: ${n}`);
