#!/usr/bin/env node
/**
 * scripts/buildUnitCounties.mjs — sample the counties that refuges + national
 * parks fall in (src/data/unitCounty.js) but which the state-park freq build
 * never covered, and MERGE them into src/data/stateParkBirdFreq.js.
 *
 * Reuses sampleCounty() from buildStateParkBirdFreq.js (shared county cache, so
 * already-built counties are skipped). PARK_COUNTY is left unchanged — refuges
 * and national parks map to their county via UNIT_COUNTY, not PARK_COUNTY.
 *
 * After this, regenerate the per-state chunks the app actually loads:
 *   node scripts/buildUnitCounties.mjs && node scripts/splitBirdFreq.mjs
 */
import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { sampleCounty } from './buildStateParkBirdFreq.js';
import { UNIT_COUNTY } from '../src/data/unitCounty.js';
import { PARK_COUNTY, COUNTY_BIRD_FREQ } from '../src/data/stateParkBirdFreq.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, '..', 'src', 'data', 'stateParkBirdFreq.js');
const CACHE_DIR = path.join(__dirname, '_nj_county_cache');

// Hard per-county cap so a stalled eBird connection can never hang the whole
// build (the documented failure mode). A county that exceeds this is cached as
// a skip so re-runs don't re-stall on it — these are the sparsest rural
// counties anyway, where the deep multi-year pass is both slowest and least
// rewarding.
const COUNTY_TIMEOUT_MS = 4 * 60 * 1000;
const writeSkip = (c) => {
  try { mkdirSync(CACHE_DIR, { recursive: true }); writeFileSync(path.join(CACHE_DIR, `${c}.json`), JSON.stringify({ __skip__: 1 })); } catch {}
};
const sampleWithCap = (c) => Promise.race([
  sampleCounty(c),
  new Promise(res => setTimeout(() => res('__TIMEOUT__'), COUNTY_TIMEOUT_MS)),
]);

async function main() {
  const have = new Set(Object.keys(COUNTY_BIRD_FREQ));
  const wanted = [...new Set(Object.values(UNIT_COUNTY))];
  const missing = wanted.filter(c => !have.has(c));
  console.log(`UNIT_COUNTY: ${wanted.length} unique counties; ${have.size} already in freq; ${missing.length} to sample.\n`);

  const freq = { ...COUNTY_BIRD_FREQ };
  let added = 0, sparse = 0, done = 0;
  const todo = [...missing];
  const worker = async () => {
    while (todo.length) {
      const c = todo.shift();
      try {
        const data = await sampleWithCap(c);
        if (data === '__TIMEOUT__') { writeSkip(c); sparse++; console.log(`  [${c}] TIMEOUT (>4m) → skip`); }
        else if (data) { freq[c] = data; added++; }
        else sparse++;
      } catch (e) { console.error(`  ! ${c}: ${e.message}`); sparse++; }
      if (++done % 20 === 0) console.log(`  …${done}/${missing.length} (${added} added, ${sparse} too-sparse/failed)`);
    }
  };
  await Promise.all(Array.from({ length: 4 }, worker));

  const body =
    `// AUTO-GENERATED by scripts/buildStateParkBirdFreq.js (+ buildUnitCounties.mjs) — do not edit.\n` +
    `// eBird county-level peak-season checklist frequency. f = peak seasonal\n` +
    `// frequency (0–1), s = present seasons. Includes refuge/national-park\n` +
    `// counties (UNIT_COUNTY) on top of the state-park counties.\n` +
    `export const PARK_COUNTY = ${JSON.stringify(PARK_COUNTY, null, 0)};\n\n` +
    `export const COUNTY_BIRD_FREQ = ${JSON.stringify(freq)};\n`;
  writeFileSync(OUT, body, 'utf8');
  const spp = Object.values(freq).reduce((n, c) => n + Object.keys(c).length, 0);
  console.log(`\n✅ Added ${added} counties (${sparse} too sparse/failed). Now ${Object.keys(freq).length} counties, ${spp} species entries.`);
  console.log(`   NEXT: node scripts/splitBirdFreq.mjs   (regenerates the per-state chunks the app loads)`);
}
main().catch(e => { console.error(e); process.exit(1); });
