#!/usr/bin/env node
/**
 * scripts/fetchNpsUnits.mjs — snapshot the natural NPS units to a static file.
 *
 *   node scripts/fetchNpsUnits.mjs
 *
 * WHY THIS EXISTS: the app discovers NPS units at RUNTIME via /api/nps-proxy,
 * so at build time there are no names or coordinates and those units got no
 * prerendered page — /park/nps_cebr served the generic SPA shell, invisible to
 * search. This writes src/data/npsUnits.js, which prerenderParks.js reads.
 *
 * Deliberately a SEPARATE, manually-run step rather than a build-time fetch:
 * `npm run build` must not fail because someone else's API is slow or down,
 * and the NPS unit list changes maybe once a year. Re-run it when it does.
 *
 * The NPS API needs a key, which lives server-side — so this goes through the
 * deployed proxy rather than holding a key here. Pass --origin to point at a
 * preview deployment instead of production.
 *
 * Filtering uses src/data/npsFilter.js, the same module the app's hook uses, so
 * the static list can never disagree with what the map actually shows.
 */
import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { npsQualifies, NP_KIND } from '../src/data/npsFilter.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : d; };
const ORIGIN = arg('--origin', 'https://wildlifeexplorer.us');
const OUT = path.join(__dirname, '..', 'src', 'data', 'npsUnits.js');

const res = await fetch(`${ORIGIN}/api/nps-proxy/parks?limit=500`);
if (!res.ok) {
  console.error(`❌ ${ORIGIN}/api/nps-proxy returned ${res.status}. ` +
    `The proxy only runs on a deployed environment — plain \`vite\` returns 403.`);
  process.exit(1);
}
const { data = [] } = await res.json();
console.log(`fetched ${data.length} NPS units from ${ORIGIN}`);

// NPS returns a handful of names with capitalised articles — "Craters Of The
// Moon", "Black Canyon Of The Gunnison". Lowercase the small words unless they
// lead the name, so pages and <title>s read the way the parks are actually
// written. Fixed here, in the snapshot, rather than at render time.
const SMALL = new Set(['of', 'the', 'and', 'at', 'in', 'on', 'for', 'a', 'an']);
const fixName = (n) => String(n).split(' ').map((w, i) =>
  i > 0 && SMALL.has(w.toLowerCase()) ? w.toLowerCase() : w).join(' ');

const units = data
  .filter(npsQualifies)
  .map(p => ({
    id: `nps_${p.parkCode}`,
    name: fixName(p.fullName),
    parkCode: p.parkCode,
    lat: Number(p.latitude),
    lng: Number(p.longitude),
    npsKind: NP_KIND(p.designation),
    stateCodes: String(p.states || '').split(',').map(s => s.trim()).filter(Boolean),
  }))
  .filter(u => Number.isFinite(u.lat) && Number.isFinite(u.lng))
  .sort((a, b) => a.id.localeCompare(b.id));

const byKind = units.reduce((m, u) => (m[u.npsKind] = (m[u.npsKind] ?? 0) + 1, m), {});

writeFileSync(OUT,
  `// Auto-generated by scripts/fetchNpsUnits.mjs — do not edit.\n` +
  `// Snapshot of the natural NPS units (${units.length}), used by the build-time\n` +
  `// SEO prerender. The running app still discovers units live via the NPS\n` +
  `// proxy; this file exists only so those units get a static page.\n` +
  `// Re-run the script if the NPS unit list changes.\n` +
  `export const NPS_UNITS = ${JSON.stringify(units, null, 0)};\n`,
  'utf8');

console.log(`✅ wrote ${units.length} units → src/data/npsUnits.js`);
for (const [k, n] of Object.entries(byKind).sort((a, b) => b[1] - a[1])) console.log(`   ${k}: ${n}`);
