// Generates src/data/nationalWildlifeRefuges.js from Wikidata.
// NWRs are instance-of (P31) Q1410668 with a coordinate (P625). State is
// assigned by point-in-polygon against the same US-states GeoJSON the app uses
// (reliable, no flaky P131 admin-chain). Run: node scripts/fetchRefuges.mjs
import { writeFileSync } from 'fs';

const UA = { Accept: 'application/sparql-results+json', 'User-Agent': 'wildlife-explorer NWR seed (+https://wildlifeexplorer.us)' };
const wdqs = async (q) => {
  const url = 'https://query.wikidata.org/sparql?format=json&query=' + encodeURIComponent(q);
  const r = await fetch(url, { headers: UA });
  if (r.status !== 200) throw new Error('WDQS ' + r.status);
  return (await r.json()).results.bindings;
};

// ── 1. All US National Wildlife Refuges with coordinates ──────────────────────
const rows = await wdqs(`SELECT ?item ?itemLabel ?lat ?lon WHERE {
  ?item wdt:P31 wd:Q1410668 .
  ?item p:P625/psv:P625 ?v . ?v wikibase:geoLatitude ?lat ; wikibase:geoLongitude ?lon .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}`);

// ── 2. US-states GeoJSON for point-in-polygon state assignment ────────────────
const geo = await (await fetch('https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json')).json();
const NAME_TO_CODE = { 'Alabama':'AL','Alaska':'AK','Arizona':'AZ','Arkansas':'AR','California':'CA','Colorado':'CO','Connecticut':'CT','Delaware':'DE','Florida':'FL','Georgia':'GA','Hawaii':'HI','Idaho':'ID','Illinois':'IL','Indiana':'IN','Iowa':'IA','Kansas':'KS','Kentucky':'KY','Louisiana':'LA','Maine':'ME','Maryland':'MD','Massachusetts':'MA','Michigan':'MI','Minnesota':'MN','Mississippi':'MS','Missouri':'MO','Montana':'MT','Nebraska':'NE','Nevada':'NV','New Hampshire':'NH','New Jersey':'NJ','New Mexico':'NM','New York':'NY','North Carolina':'NC','North Dakota':'ND','Ohio':'OH','Oklahoma':'OK','Oregon':'OR','Pennsylvania':'PA','Rhode Island':'RI','South Carolina':'SC','South Dakota':'SD','Tennessee':'TN','Texas':'TX','Utah':'UT','Vermont':'VT','Virginia':'VA','Washington':'WA','West Virginia':'WV','Wisconsin':'WI','Wyoming':'WY' };
const inRing = (lng, lat, ring) => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1], xj = ring[j][0], yj = ring[j][1];
    if (((yi > lat) !== (yj > lat)) && (lng < (xj - xi) * (lat - yi) / (yj - yi) + xi)) inside = !inside;
  }
  return inside;
};
const stateOf = (lat, lng) => {
  for (const f of geo.features) {
    const code = NAME_TO_CODE[f.properties.name];
    if (!code) continue;
    const g = f.geometry;
    const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
    for (const poly of polys) if (inRing(lng, lat, poly[0])) return code;
  }
  return null;
};

// ── 3. Clean + build location objects ─────────────────────────────────────────
const slug = s => s.toLowerCase().replace(/national wildlife refuge.*/,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const seen = new Set();
const out = [];
let noState = 0;
for (const b of rows) {
  const name = b.itemLabel.value;
  const lat = +(+b.lat.value).toFixed(4), lng = +(+b.lon.value).toFixed(4);
  if (!(lat > 17 && lat < 72 && lng > -180 && lng < -64)) continue;        // US bounds
  if (!/National Wildlife Refuge$/.test(name)) continue;                    // exact unit, drop sub-features
  const id = 'nwr_' + slug(name);
  if (seen.has(id)) continue; seen.add(id);
  const code = stateOf(lat, lng);
  if (!code) noState++;
  out.push({ id, name, lat, lng, code });
}
out.sort((a,b) => a.name.localeCompare(b.name));

const body =
`// National Wildlife Refuges (USFWS) — auto-generated by scripts/fetchRefuges.mjs
// from Wikidata (P31 = Q1410668). ${out.length} units. Opt-in layer on the
// national map (locationType 'wildlifeRefuge'); species fetched live by lat/lng.
export const NATIONAL_WILDLIFE_REFUGES = [
${out.map(r => `  { id: '${r.id}', name: ${JSON.stringify(r.name)}, lat: ${r.lat}, lng: ${r.lng}, locationType: 'wildlifeRefuge', npsKind: 'Wildlife Refuge', stateCodes: ${r.code ? `['${r.code}']` : '[]'}, radiusKm: 8, animals: [] },`).join('\n')}
];
`;
writeFileSync(new URL('../src/data/nationalWildlifeRefuges.js', import.meta.url), body);
console.log(`Wrote ${out.length} refuges (${noState} without a state match).`);
