#!/usr/bin/env node
/**
 * scripts/fixDescriptions2.js — Second pass: add real descriptions for
 * remaining high-visibility animals that got type-templates in pass 1.
 */
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'src', 'data');

const mod = await import('../src/data/wildlifeCache.js');
const cache = {};
for (const [id, val] of Object.entries(mod.WILDLIFE_CACHE)) {
  cache[id] = { ...val, animals: val.animals.map(a => ({ ...a })) };
}

// Only replace funFacts that were generated by pass-1 templates (not curated ones)
function isTemplated(ff) {
  if (!ff) return false;
  if (/is a (?:summer-breeding|winter-visiting|migratory|year-round resident) bird species documented/.test(ff)) return true;
  if (/is a bird species documented in this park through eBird/.test(ff)) return true;
  if (/is a mammal inhabiting this park/.test(ff)) return true;
  if (/is a reptile species found in this park/.test(ff)) return true;
  if (/is an amphibian found near water sources/.test(ff)) return true;
  if (/is an invertebrate documented in this park/.test(ff)) return true;
  if (/is a marine species found in waters near/.test(ff)) return true;
  return false;
}

const EXTRA_DESCRIPTIONS = {
  // ── Birds remaining from top list ──────────────────────────────────────────
  'trumpeter swan': 'Trumpeter Swans are the largest waterfowl in North America with wingspans over 8 feet. Nearly hunted to extinction by the 1930s, they have been successfully restored to the northern lakes and rivers.',
  'red-bellied woodpecker': 'Red-bellied Woodpeckers have a bright red cap and a finely barred black-and-white back. Despite their name, the red belly patch is faint — look for the vivid red on their head instead.',
  'hairy woodpecker': 'Hairy Woodpeckers are medium-sized, boldly patterned black-and-white woodpeckers that drum loudly on dead trees. They follow other woodpeckers to steal insects exposed by the excavation.',
  'ruffed grouse': 'Ruffed Grouse are chicken-sized forest birds known for the male\'s thundering "drumming" display — a deep, accelerating thumping created by rapidly beating wings against the air.',
  'brown noddy': 'Brown Noddies are tropical seabirds that nest in dense colonies on remote islands. Unlike most terns, they dip to the surface rather than plunge-diving, snatching small fish with precision.',
  'magnificent frigatebird': 'Magnificent Frigatebirds are masterful aerialists with 7-foot wingspans that soar for days without landing. Males inflate a brilliant red throat pouch during courtship displays.',
  'ring-billed gull': 'Ring-billed Gulls are medium-sized gulls identified by the black ring near the tip of their yellow bill. They are one of the most abundant and adaptable gulls in North America.',
  'white-throated swift': 'White-throated Swifts are among the fastest-flying birds in North America, rocketing along cliff faces at speeds over 100 mph. They nest in narrow rock crevices in canyon walls.',
  'broad-tailed hummingbird': 'Broad-tailed Hummingbirds are mountain-dwelling jewels whose males produce a distinctive metallic trilling with their wing feathers in flight. They can enter torpor on cold nights to conserve energy.',
  'american coot': 'American Coots are dark, chicken-like waterbirds with white bills that bob their heads while swimming. Despite lacking webbed feet, they have lobed toes that make them strong swimmers and divers.',
  "woodhouse's scrub-jay": "Woodhouse's Scrub-Jays are slender, crestless blue jays of the arid West that cache thousands of seeds and nuts. They are bold and curious, often approaching hikers for handouts.",
  'house finch': 'House Finches are small, energetic songbirds where males sport rosy-red heads and breasts. Originally native to the western US and Mexico, they have spread across the entire continent.',
  'cinnamon teal': 'Cinnamon Teal are small dabbling ducks where males glow a rich cinnamon-red in breeding plumage. They are the only duck species that breeds in both North and South America.',
  'american wigeon': 'American Wigeons are medium-sized dabbling ducks with a distinctive white forehead patch on males. They often steal aquatic vegetation from diving ducks and coots rather than diving themselves.',
  'white-winged dove': 'White-winged Doves are stocky desert doves with bold white wing patches visible in flight. Their cooing call is a signature sound of the Sonoran Desert.',
  "say's phoebe": "Say's Phoebes are slender, tail-pumping flycatchers of open arid country. They perch on fence posts and rocks, sallying out to snatch insects mid-air, and often nest on building ledges.",
  'rock pigeon': 'Rock Pigeons are the familiar "city pigeons" descended from wild cliff-dwelling birds of Europe. In parks, they revert to nesting on natural cliff faces and rock ledges.',
  'mourning dove': 'Mourning Doves are slender, graceful birds with long pointed tails and a soft, mournful cooing call. They are among the most abundant birds in North America.',
  'black-chinned hummingbird': 'Black-chinned Hummingbirds are small, adaptable hummingbirds with a thin strip of iridescent purple below their black throat. They pump their tails constantly while hovering at flowers.',
  'california gull': 'California Gulls are medium-sized gulls famous for saving Utah\'s crops from a cricket plague in 1848. They breed at inland lakes and winter along the Pacific coast.',
  'belted kingfisher': 'Belted Kingfishers are stocky, crested birds that hover over water before plunging headfirst to catch fish. The female is more colorful than the male, with an additional rusty belly band.',
  'rufous hummingbird': 'Rufous Hummingbirds are feisty, coppery-orange hummingbirds that migrate farther than any other hummingbird relative to body size — over 3,000 miles from Mexico to Alaska.',
  'band-tailed pigeon': 'Band-tailed Pigeons are large, gray forest pigeons with a white crescent on the nape and a yellow bill. They feed on acorns and berries in the canopy of western mountain forests.',
  'glaucous-winged gull': 'Glaucous-winged Gulls are large, pale-winged gulls common along the Pacific Northwest coast. They are opportunistic feeders that eat everything from fish to french fries.',
  'bufflehead': 'Buffleheads are tiny, energetic diving ducks where males flash striking black-and-white plumage with an iridescent purple-green head. They nest in old woodpecker holes near lakes.',
  "anna's hummingbird": "Anna's Hummingbirds are year-round residents of the Pacific Coast with iridescent rose-pink throats and crowns on males. They are among the few hummingbirds that sing a buzzy, scratchy song.",
  'black phoebe': 'Black Phoebes are sleek, jet-black flycatchers with crisp white bellies that pump their tails while perched near water. They build mud nests under bridges and eaves.',
  'dark-eyed junco': 'Dark-eyed Juncos are small, slate-colored sparrows that flash white outer tail feathers when they fly. Often called "snowbirds," they are one of the most common forest birds in North America.',
  'california quail': "California Quail are plump ground birds with a distinctive forward-drooping topknot plume. Family groups called coveys scurry single-file through brush, the male standing sentinel on a post.",
  'ring-necked duck': 'Ring-necked Ducks are diving ducks with a distinctive white ring on their bill, which is more visible than the faint chestnut neck ring. They prefer sheltered ponds and marshy lakes.',
  'northern shoveler': 'Northern Shovelers have oversized, spatula-shaped bills that they sweep through water to filter tiny crustaceans and seeds. Groups often swim in tight circles to concentrate food.',
  'california scrub-jay': 'California Scrub-Jays are sleek, crestless blue jays that cache acorns and show remarkable memory. Studies have shown they can plan for the future and deceive other jays about cache locations.',
  'tufted puffin': 'Tufted Puffins are stocky seabirds with bright orange bills and sweeping golden head plumes during breeding season. They nest in burrows on sea cliffs and "fly" underwater to catch fish.',
  'pigeon guillemot': 'Pigeon Guillemots are small, dark seabirds with bright red feet and white wing patches. They nest in rock crevices along the coast and dive to catch small fish near the seafloor.',
  'black-legged kittiwake': 'Black-legged Kittiwakes are graceful, cliff-nesting gulls of the open ocean named for their distinctive "kittiwake" call. They are the most pelagic of all gulls.',
  'green-winged teal': 'Green-winged Teal are North America\'s smallest dabbling ducks, with males showing a distinctive green ear patch and cinnamon head. They burst from the water almost vertically when startled.',
  'canada jay': 'Canada Jays are fluffy, gray-and-white corvids of the boreal forest that boldly approach hikers and campers. They cache thousands of food items using sticky saliva to glue them to tree bark.',
  'hawaiian goose': 'The Hawaiian Goose (Nene) is the world\'s rarest goose and Hawaii\'s state bird. Descended from Canada Geese that arrived roughly 500,000 years ago, they have adapted to walking on rough lava flows.',
  'barn swallow': 'Barn Swallows are sleek, aerial acrobats with deeply forked tails that catch insects on the wing. They build cup-shaped mud nests under eaves, bridges, and cliff overhangs.',
  'northern mockingbird': 'Northern Mockingbirds are virtuoso singers that can mimic over 200 songs of other birds, plus car alarms and cell phone rings. They sing prolifically, even at night during breeding season.',
  'pinyon jay': 'Pinyon Jays are blue, crestless corvids that roam in noisy flocks of up to 500 birds through pinyon-juniper woodlands. Their partnership with pinyon pines is crucial — they plant the seeds that grow new trees.',
  'ring-necked pheasant': 'Ring-necked Pheasants are large, colorful game birds introduced from Asia, with males sporting iridescent green heads and bold white neck rings. They burst from grasslands with a startling cackle.',
  'prothonotary warbler': 'Prothonotary Warblers are brilliant golden-yellow swamp warblers that nest in tree cavities near water. Their name comes from the golden robes worn by Vatican clerks.',
  'least sandpiper': 'Least Sandpipers are the smallest shorebirds in the world, barely larger than a sparrow. They feed on mudflats with a distinctive hunched posture, probing mud with their thin bills.',
  'common goldeneye': 'Common Goldeneyes are striking diving ducks with bright yellow eyes and bold black-and-white plumage on males. Their wings produce a distinctive whistling sound in flight.',
  "swainson's thrush": "Swainson's Thrushes are olive-brown songbirds with buffy eye-rings and one of the most beautiful songs in the boreal forest — an ascending, spiraling flute-like melody heard at dusk.",
  'surf scoter': 'Surf Scoters are large, dark sea ducks with boldly patterned orange-and-white bills on males. They dive in the surf zone along rocky coasts to feed on mussels and other shellfish.',

  // ── Mammals ────────────────────────────────────────────────────────────────
  'american red squirrel': 'American Red Squirrels are small, fiery-tempered squirrels that chatter loudly at intruders from conifer branches. They harvest and cache enormous piles of spruce cones called "middens."',
  'columbian ground squirrel': 'Columbian Ground Squirrels are chunky, reddish-furred ground squirrels that stand upright like sentinels in alpine meadows. They hibernate for 7-8 months, among the longest of any mammal.',
  'uinta chipmunk': 'Uinta Chipmunks are small, boldly striped rodents found in mountain conifer forests. Active and vocal, they stuff their expandable cheek pouches with seeds before retreating to underground caches.',
  'hopi chipmunk': 'Hopi Chipmunks are tiny, pale desert chipmunks that scurry across sandstone ledges and slickrock. They are well-adapted to arid canyon country and are frequently spotted at overlooks.',
  'eurasian wild pig': 'Eurasian Wild Pigs are destructive invasive mammals that root through forest floors, destroying native plant communities and salamander habitat. Removal efforts in parks are ongoing.',

  // ── Reptiles/Amphibians ────────────────────────────────────────────────────
  'brown anole': 'Brown Anoles are small, invasive lizards from Cuba and the Bahamas that have become extremely abundant in South Florida. Males bob their heads and flash a red-orange throat fan to defend territory.',
  'florida cottonmouth': 'Florida Cottonmouths are heavy-bodied venomous snakes that open their mouths wide to reveal the white "cotton" lining as a warning display. They inhabit swamps, marshes, and slow-moving waterways.',
  'florida red-bellied cooter': 'Florida Red-bellied Cooters are large freshwater turtles often seen basking in groups on logs. They are primarily herbivorous, grazing on aquatic vegetation in marshes and canals.',
  'florida softshell turtle': 'Florida Softshell Turtles have flat, leathery shells and long snorkel-like noses. They bury themselves in sand or mud at the bottom of ponds, ambushing fish and crayfish.',
  'painted turtle': 'Painted Turtles are colorful freshwater turtles with red and yellow markings on their shells and skin. They bask on logs in groups, sliding into the water at the slightest disturbance.',
  'common snapping turtle': 'Common Snapping Turtles are large, prehistoric-looking turtles with powerful jaws and spiked tails. Generally docile in water, they become defensive on land — give them wide berth.',
  'common garter snake': 'Common Garter Snakes are harmless, striped snakes found near water in almost every habitat. They emerge in large numbers from communal dens in spring, sometimes forming writhing mating balls.',
  'eastern red-backed salamander': 'Eastern Red-backed Salamanders are tiny, lungless salamanders that breathe through their moist skin. Despite their small size, they are the most abundant vertebrate in many eastern forests.',
  'plateau fence lizard': 'Plateau Fence Lizards are small, gray-brown lizards commonly seen doing push-ups on sun-warmed rocks and fence posts. Males flash bright blue belly patches to defend territory.',
  'six-lined racerunner': 'Six-lined Racerunners are lightning-fast lizards with six yellow stripes running down their dark bodies. They sprint in short bursts across sandy ground, reaching speeds of 18 mph.',
  'eastern hognose snake': 'Eastern Hognose Snakes are harmless, drama-queen snakes that flatten their necks like cobras, hiss loudly, and if that fails, roll over and play dead with tongue lolling out.',
  'zebra-tailed lizard': 'Zebra-tailed Lizards are fast desert lizards that curl their black-and-white banded tail over their back while running, creating a hypnotic pattern to confuse predators.',
  'crested anole': 'Crested Anoles are small, green-brown lizards common on tree trunks and walls in the Caribbean. Males extend a bright yellow-orange dewlap to attract mates and defend territory.',
  'common sagebrush lizard': 'Common Sagebrush Lizards are small, quick lizards with rough, spiny scales found in dry, rocky sagebrush habitats. Males display blue belly patches during territorial disputes.',

  // ── Insects/Invertebrates ──────────────────────────────────────────────────
  'eastern tiger swallowtail': 'Eastern Tiger Swallowtails are large, striking butterflies with yellow wings marked by black tiger stripes. They are frequent visitors to gardens and wildflower meadows from spring through fall.',
  'pipevine swallowtail': 'Pipevine Swallowtails are iridescent blue-black butterflies that are toxic to predators from eating pipevine plants as caterpillars. Several other butterfly species mimic their appearance.',
  'mammoth cave cricket': 'Mammoth Cave Crickets are large, pale cave-dwelling insects with enormously long antennae that sense their pitch-dark environment. They leave the cave at night to forage in the forest.',
  'california sister': 'California Sisters are striking butterflies with bold orange-tipped black-and-white wing bands. They glide through oak woodlands with stiff, sailing wingbeats, rarely visiting flowers.',
  'six-spotted tiger beetle': 'Six-spotted Tiger Beetles are metallic green predators with incredible speed — relative to their size, they are one of the fastest animals on Earth, running down prey on forest paths.',
  'tricolored bumble bee': 'Tricolored Bumble Bees are important native pollinators with distinctive orange, black, and yellow banding. Once common, their populations have declined sharply, making sightings noteworthy.',
  'common eastern bumble bee': 'Common Eastern Bumble Bees are large, fuzzy pollinators with yellow-and-black banding that visit a wide variety of wildflowers. They live in underground colonies of 50-400 workers.',

  // ── Marine ─────────────────────────────────────────────────────────────────
  'gray snapper': 'Gray Snappers are common reef fish found in mangroves, seagrass beds, and coral reefs. They are curious and often approach snorkelers, making them one of the most frequently seen fish in tropical waters.',
  'sockeye salmon': 'Sockeye Salmon turn brilliant crimson during their upstream spawning run, providing a critical food source for bears, eagles, and entire ecosystems. They die after spawning, fertilizing the streams.',
};

let fixed = 0;
for (const [parkId, parkData] of Object.entries(cache)) {
  if (!parkData?.animals) continue;
  for (const animal of parkData.animals) {
    const key = animal.name.toLowerCase();
    if (EXTRA_DESCRIPTIONS[key] && isTemplated(animal.funFact)) {
      animal.funFact = EXTRA_DESCRIPTIONS[key];
      fixed++;
    }
  }
}

console.log(`Pass 2: ${fixed} animal entries updated with real descriptions`);

// Verify: count remaining templated funFacts
let templatedRemaining = 0;
for (const parkData of Object.values(cache)) {
  if (!parkData?.animals) continue;
  for (const a of parkData.animals) {
    if (isTemplated(a.funFact)) templatedRemaining++;
  }
}
console.log(`Remaining templated funFacts: ${templatedRemaining} of 32091`);

// Write
const builtAt = new Date().toISOString();
const allParkIds = Object.keys(cache);
const totalSpecies = Object.values(cache).reduce((s, v) => s + (v.animals?.length ?? 0), 0);

const lines = [
  `// Auto-generated by scripts/buildWildlifeCache.js -- do not edit manually.`,
  `// Built: ${builtAt}`,
  `// Parks: ${allParkIds.length} | Species bundled: ${totalSpecies}`,
  `// To regenerate: node scripts/buildWildlifeCache.js`,
  `// Descriptions pass 2: ${new Date().toISOString().slice(0, 10)} via fixDescriptions2.js`,
  ``,
  `export const WILDLIFE_CACHE_BUILT_AT = ${JSON.stringify(builtAt)};`,
  ``,
  `export const WILDLIFE_CACHE = {`,
];

for (const [id, val] of Object.entries(cache)) {
  lines.push(`  ${JSON.stringify(id)}: {`);
  lines.push(`    builtAt: ${JSON.stringify(val.builtAt)},`);
  lines.push(`    animals: ${JSON.stringify(val.animals, null, 2).replace(/\n/g, '\n    ')},`);
  lines.push(`  },`);
}
lines.push(`};`);
lines.push(``);

writeFileSync(path.join(DATA_DIR, 'wildlifeCache.js'), lines.join('\n'), 'utf8');
console.log(`Written: wildlifeCache.js (${totalSpecies} species)`);
