'use strict';
/**
 * fixExceptional.cjs — Downgrade over-pessimistic "exceptional" animals to "rare"
 *
 * Rules applied to EVERY park:
 *  1. iNat-sourced animal whose funFact is "N research-grade iNaturalist observations
 *     at this park" (N >= 1) → rare
 *  2. NPS-sourced animal whose funFact is "Officially documented in the NPS wildlife
 *     registry" (= 0 visitor observations) → rare
 *  3. Preserve explicit "exceptional" overrides: Florida Panther @ everglades,
 *     American Bison @ grandcanyon, American Alligator @ drytortugas — these are
 *     handled by RARITY_OVERRIDES in apiService.js and should stay exceptional in cache
 *     so the override is meaningful.
 *
 * Run: node scripts/fixExceptional.cjs
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const ROOT       = path.join(__dirname, '..');
const CACHE_PATH = path.join(ROOT, 'src', 'data', 'wildlifeCache.js');

// These (park, name) pairs are intentionally exceptional — protect them.
const KEEP_EXCEPTIONAL = new Set([
  'everglades|Florida Panther',
  'grandcanyon|American Bison',
  'drytortugas|American Alligator',
  'biscayne|American Alligator',     // drytortugas override bleeds here too
]);

// Regex patterns for the two placeholder funFact types
const INAT_FEW_OBS_RE  = /^(\d+) research-grade iNaturalist observations at this park\.?$/i;
const NPS_REGISTRY_RE  = /^Officially documented in the NPS wildlife registry/i;
const NPS_INVENTORY_RE = /^Listed in the NPS species inventory/i;

function loadCache() {
  const src = fs.readFileSync(CACHE_PATH, 'utf8');
  const cjs = src
    .replace('export const WILDLIFE_CACHE_BUILT_AT', 'const WILDLIFE_CACHE_BUILT_AT')
    .replace('export const WILDLIFE_CACHE', 'const WILDLIFE_CACHE')
    + '\nmodule.exports = { WILDLIFE_CACHE, WILDLIFE_CACHE_BUILT_AT };';
  const tmp = path.join(os.tmpdir(), '_fixexc_tmp.cjs');
  fs.writeFileSync(tmp, cjs);
  delete require.cache[require.resolve(tmp)];
  const mod = require(tmp);
  fs.unlinkSync(tmp);
  return { cache: mod.WILDLIFE_CACHE, builtAt: mod.WILDLIFE_CACHE_BUILT_AT };
}

function saveCache(cache, builtAt) {
  const ts = new Date().toISOString();
  let out = `// Auto-generated by scripts/buildWildlifeCache.js — do not edit manually.\n`;
  out += `// Built: ${builtAt}\n`;
  out += `// Exceptional fix applied: ${ts}\n`;
  out += `// Parks: ${Object.keys(cache).length} | Species bundled: ${Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0)}\n\n`;
  out += `export const WILDLIFE_CACHE_BUILT_AT = "${builtAt}";\n\n`;
  out += `export const WILDLIFE_CACHE = ${JSON.stringify(cache, null, 2)};\n\nexport default WILDLIFE_CACHE;\n`;
  fs.writeFileSync(CACHE_PATH, out, 'utf8');
}

function shouldDowngrade(parkId, animal) {
  if (animal.rarity !== 'exceptional') return false;
  // Protect intentional exceptions
  if (KEEP_EXCEPTIONAL.has(`${parkId}|${animal.name}`)) return false;

  const funFact = animal.funFact?.trim() || '';
  const source  = animal.source || '';
  const sources = animal.sources || [];

  // Rule 1: iNat animal with ≥1 research-grade obs → rare
  const m = INAT_FEW_OBS_RE.exec(funFact);
  if (m) return true; // 1-4 obs (or any N) confirmed sighting → rare

  // Rule 2: NPS registry / inventory with no visitor obs → rare
  if ((NPS_REGISTRY_RE.test(funFact) || NPS_INVENTORY_RE.test(funFact)) &&
      (source === 'nps' || sources.includes('nps'))) return true;

  return false;
}

function main() {
  console.log('══════════════════════════════════════════════════');
  console.log('  Fix over-pessimistic "exceptional" → "rare"');
  console.log('══════════════════════════════════════════════════\n');

  const { cache, builtAt } = loadCache();

  const TARGET_PARKS = ['windcave','badlands','biscayne','theodoreroosevelt','mammothcave','voyageurs'];

  // Before stats
  console.log('Before:');
  for (const pid of TARGET_PARKS) {
    const animals = cache[pid]?.animals || [];
    const exc = animals.filter(a => a.rarity === 'exceptional').length;
    console.log(`  ${pid}: ${exc}/${animals.length} exceptional (${((exc/animals.length)*100).toFixed(1)}%)`);
  }

  // Apply fix — ALL parks, not just target parks
  let totalFixed = 0;
  const byPark = {};

  for (const [parkId, parkData] of Object.entries(cache)) {
    let parkFixed = 0;
    for (const animal of parkData.animals || []) {
      if (shouldDowngrade(parkId, animal)) {
        animal.rarity = 'rare';
        parkFixed++;
        totalFixed++;
      }
    }
    if (parkFixed > 0) byPark[parkId] = parkFixed;
  }

  // After stats
  console.log('\nAfter:');
  for (const pid of TARGET_PARKS) {
    const animals = cache[pid]?.animals || [];
    const exc = animals.filter(a => a.rarity === 'exceptional').length;
    const rare = animals.filter(a => a.rarity === 'rare').length;
    console.log(`  ${pid}: ${exc}/${animals.length} exceptional (${((exc/animals.length)*100).toFixed(1)}%) | rare: ${rare}`);
  }

  console.log(`\nTotal animals downgraded exceptional→rare: ${totalFixed}`);
  console.log('Parks affected: ' + Object.keys(byPark).sort().join(', '));

  // Verify protected exceptions still correct
  const panther = cache.everglades?.animals?.find(a => a.name === 'Florida Panther');
  const bison   = cache.grandcanyon?.animals?.find(a => a.name === 'American Bison');
  console.log(`\nProtected species check:`);
  console.log(`  Florida Panther @ everglades: ${panther?.rarity} ${panther?.rarity === 'exceptional' ? '✅' : '❌'}`);
  console.log(`  American Bison @ grandcanyon: ${bison?.rarity} ${bison?.rarity === 'exceptional' ? '✅' : '❌'}`);

  saveCache(cache, builtAt);
  const total = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0);
  console.log(`\n✓ Written: ${total} total animals`);
}

main();
