'use strict';
/**
 * followUpAudit.cjs — Three-part post-fix audit
 *  1. Verify 126 new animals (rarity, photos)
 *  2. Marine life completeness at 7 coastal parks
 *  3. Find + fix animals missing descriptions
 *
 * Run: node scripts/followUpAudit.cjs
 * Options:
 *   SKIP_MARINE=1   — skip iNat API calls (task 2)
 *   SKIP_DESC=1     — skip description enrichment (task 3)
 *   DRY_RUN=1       — don't write to wildlifeCache.js
 */

const fs    = require('fs');
const path  = require('path');
const https = require('https');
const os    = require('os');

const ROOT = path.join(__dirname, '..');
const CACHE_PATH = path.join(ROOT, 'src', 'data', 'wildlifeCache.js');

const SKIP_MARINE = process.env.SKIP_MARINE === '1';
const SKIP_DESC   = process.env.SKIP_DESC   === '1';
const DRY_RUN     = process.env.DRY_RUN     === '1';

// ── load cache ──────────────────────────────────────────────────────────────
function loadCache() {
  const src = fs.readFileSync(CACHE_PATH, 'utf8');
  const cjs = src
    .replace('export const WILDLIFE_CACHE_BUILT_AT', 'const WILDLIFE_CACHE_BUILT_AT')
    .replace('export const WILDLIFE_CACHE', 'const WILDLIFE_CACHE')
    + '\nmodule.exports = { WILDLIFE_CACHE, WILDLIFE_CACHE_BUILT_AT };';
  const tmp = path.join(os.tmpdir(), '_followup_cache_tmp.cjs');
  fs.writeFileSync(tmp, cjs);
  delete require.cache[require.resolve(tmp)];
  const mod = require(tmp);
  fs.unlinkSync(tmp);
  return { cache: mod.WILDLIFE_CACHE, builtAt: mod.WILDLIFE_CACHE_BUILT_AT };
}

function saveCache(cache, builtAt) {
  const ts = new Date().toISOString();
  let out = `// Auto-generated by scripts/buildWildlifeCache.js — do not edit manually.\n`;
  out += `// Built: ${builtAt}\n`;
  out += `// Audit follow-up applied: ${ts}\n`;
  out += `// Parks: ${Object.keys(cache).length} | Species bundled: ${Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0)}\n\n`;
  out += `export const WILDLIFE_CACHE_BUILT_AT = "${builtAt}";\n\n`;
  out += `export const WILDLIFE_CACHE = ${JSON.stringify(cache, null, 2)};\n\nexport default WILDLIFE_CACHE;\n`;
  fs.writeFileSync(CACHE_PATH, out, 'utf8');
}

// ── HTTP helper ─────────────────────────────────────────────────────────────
function fetchJson(url, headers = {}) {
  return new Promise(resolve => {
    const u = new URL(url);
    const req = https.request({
      hostname: u.hostname,
      path: u.pathname + u.search,
      headers: { 'User-Agent': 'WildlifeMap-AuditFollowUp/1.0', ...headers },
    }, res => {
      let data = '';
      res.on('data', d => data += d);
      res.on('end', () => { try { resolve(JSON.parse(data)); } catch { resolve(null); } });
    });
    req.on('error', () => resolve(null));
    req.setTimeout(15000, () => { req.destroy(); resolve(null); });
    req.end();
  });
}
const sleep = ms => new Promise(r => setTimeout(r, ms));

// ── iNat taxon lookup ────────────────────────────────────────────────────────
const _taxonCache = {};
async function fetchTaxon(name, sciName) {
  const key = sciName || name;
  if (_taxonCache[key] !== undefined) return _taxonCache[key];
  const q   = encodeURIComponent(sciName || name);
  const url = `https://api.inaturalist.org/v1/taxa?q=${q}&rank=species,subspecies&per_page=3&locale=en`;
  const data = await fetchJson(url);
  await sleep(350);
  if (!data?.results?.length) { _taxonCache[key] = null; return null; }
  let t = data.results.find(x => x.name?.toLowerCase() === (sciName||'').toLowerCase())
       || data.results.find(x => (x.preferred_common_name||'').toLowerCase() === name.toLowerCase())
       || data.results[0];
  const result = {
    photoUrl:    t.default_photo?.medium_url || null,
    description: t.wikipedia_summary || null,
  };
  _taxonCache[key] = result;
  return result;
}

// ── iNat place IDs ───────────────────────────────────────────────────────────
const INAT_PLACE_IDS = {
  channelislands: 3157, kenaifjords: 95258, biscayne: 95108,
  virginislands: 95336, olympic: 69094, acadia: 49610, drytortugas: 70571,
  // extras used for description lookups
  saguaro: 65739, glacier: 72841, grandcanyon: 69216, zion: 50634,
};

// ═══════════════════════════════════════════════════════════════════════════
// TASK 1 — Verify new animals
// ═══════════════════════════════════════════════════════════════════════════
async function task1_verifyNewAnimals(cache) {
  console.log('\n══════════════════════════════════════════════════');
  console.log('  TASK 1 — Verify new animals from applyAuditFixes');
  console.log('══════════════════════════════════════════════════\n');

  // Key spot checks — (park, name, expectedRarity)
  const SPOT_CHECKS = [
    ['saguaro',          'Desert Spiny Lizard',                'guaranteed'],
    ['arches',           'Common Side-blotched Lizard',        'very_likely'],
    ['yosemite',         'Western Fence Lizard',               'very_likely'],
    ['virginislands',    'Green Sea Turtle',                   'unlikely'],
    ['glacier',          'Hoary Marmot',                       'very_likely'],
    ['glacier',          'Columbian Ground Squirrel',          'very_likely'],
    ['grandcanyon',      'Elk',                                'likely'],
    ['greatsmokymountains','Elk',                              'likely'],
    ['zion',             'Desert Bighorn Sheep',               'very_likely'],
    ['windcave',         'Mule Deer',                          'likely'],
    ['everglades',       'American Crocodile',                 'unlikely'],
    ['saguaro',          'Western Diamond-backed Rattlesnake', 'likely'],
    ['saguaro',          'Zebra-tailed Lizard',                'very_likely'],
    ['gatewayarch',      'American Toad',                      'likely'],
    ['gatewayarch',      'Pond Slider',                        'likely'],
    ['gatewayarch',      'American Bullfrog',                  'likely'],
    ['biscayne',         'Crested Anole',                      'very_likely'],
    ['biscayne',         'American Crocodile',                 'likely'],
    ['mountrainier',     'Pacific Chorus Frog',                'likely'],
    ['mountrainier',     'Cascades Frog',                      'likely'],
    ['redwood',          'Ensatina',                           'likely'],
    ['redwood',          'Northern Red-legged Frog',           'likely'],
    ['hotsprings',       'Three-toed Box Turtle',              'likely'],
    ['drytortugas',      'Green Sea Turtle',                   'unlikely'],
    ['haleakala',        'Green Sea Turtle',                   'unlikely'],
    ['joshuatree',       'Common Side-blotched Lizard',        'very_likely'],
    ['joshuatree',       'Common Chuckwalla',                  'very_likely'],
  ];

  let pass = 0, fail = 0;
  const photoCheck = [];
  console.log('Spot checks:');
  for (const [park, name, exp] of SPOT_CHECKS) {
    const a = cache[park]?.animals?.find(x => x.name === name);
    const ok = a && a.rarity === exp;
    console.log(`  ${ok ? '✅' : '❌'} ${park} / ${name} = ${a?.rarity || 'MISSING'} (want ${exp})`);
    if (ok) pass++; else fail++;
    if (a) photoCheck.push({ park, name, photoUrl: a.photoUrl, sciName: a.scientificName });
  }
  console.log(`\nSpot check result: ${pass} pass, ${fail} fail`);

  // Count new animals with/without photos
  const newSpecies = [
    'Elk','Hoary Marmot','Columbian Ground Squirrel','Common Side-blotched Lizard',
    'Plateau Fence Lizard','Western Fence Lizard','Desert Spiny Lizard',
    'Western Diamond-backed Rattlesnake','Zebra-tailed Lizard','American Toad',
    'Pond Slider','American Bullfrog','Crested Anole','Southern Toad',
    'Florida Softshell Turtle','Florida Cottonmouth','American Crocodile',
    'Pacific Chorus Frog','Northwestern Salamander','Western Toad','Cascades Frog',
    'Ensatina','Northern Red-legged Frog','California Slender Salamander',
    'Three-toed Box Turtle','Common Box Turtle','Green Sea Turtle',
    'Common Chuckwalla','Gopher Snake','Western Terrestrial Garter Snake',
    'Columbia Spotted Frog','Western Tiger Salamander','Rough-skinned Newt',
    'Hawksbill Sea Turtle','Eastern Collared Lizard',
  ];
  let withPhoto = 0, noPhoto = 0;
  const noPhotoList = [];
  for (const sp of newSpecies) {
    // find any park with this animal
    for (const [parkId, parkData] of Object.entries(cache)) {
      const a = parkData.animals?.find(x => x.name === sp);
      if (a) {
        if (a.photoUrl) withPhoto++;
        else { noPhoto++; noPhotoList.push(`${sp} @ ${parkId}`); }
        break; // just check one instance per species
      }
    }
  }
  console.log(`\nPhoto coverage for new species (one instance each):`);
  console.log(`  ${withPhoto} have photos, ${noPhoto} missing photos`);
  if (noPhotoList.length) {
    console.log('  Missing photos:');
    noPhotoList.forEach(x => console.log('    ' + x));
  }

  // Total new animals summary
  const total = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0);
  console.log(`\nTotal animals in cache: ${total}`);
}

// ═══════════════════════════════════════════════════════════════════════════
// TASK 2 — Marine life completeness
// ═══════════════════════════════════════════════════════════════════════════
const MARINE_PARKS = [
  { id: 'channelislands', name: 'Channel Islands' },
  { id: 'kenaifjords',    name: 'Kenai Fjords'    },
  { id: 'biscayne',       name: 'Biscayne'        },
  { id: 'virginislands',  name: 'Virgin Islands'  },
  { id: 'olympic',        name: 'Olympic'         },
  { id: 'acadia',         name: 'Acadia'          },
  { id: 'drytortugas',    name: 'Dry Tortugas'    },
];

// iNat iconic_taxa that map to our 'marine' type
const MARINE_TAXA = [
  { taxa: 'Actinopterygii', label: 'Fish'     },
  { taxa: 'Mollusca',       label: 'Mollusks' },
  { taxa: 'Echinodermata',  label: 'Echinoderms' },
  { taxa: 'Animalia',       label: 'Other Marine', filter: true }, // will filter by presence in marine zone
];

async function fetchTopMarineForPark(placeId) {
  const results = [];
  for (const taxonGroup of ['Actinopterygii', 'Mollusca', 'Echinodermata']) {
    const url = `https://api.inaturalist.org/v1/observations/species_counts` +
      `?place_id=${placeId}&iconic_taxa[]=${taxonGroup}&quality_grade=research` +
      `&order_by=observations_count&order=desc&per_page=15&locale=en`;
    const data = await fetchJson(url);
    await sleep(600);
    if (!data?.results) continue;
    for (const r of data.results) {
      const obs = r.count ?? 0;
      if (obs < 50) continue; // only well-documented species
      const commonName = r.taxon?.preferred_common_name || r.taxon?.name;
      if (!commonName) continue;
      results.push({
        name: commonName,
        sciName: r.taxon?.name,
        obs,
        taxonGroup,
      });
    }
  }
  // Sort by obs count descending
  results.sort((a, b) => b.obs - a.obs);
  return results;
}

function rarityFromObs(obs, name) {
  const n = name?.toLowerCase() || '';
  // Apply charisma corrections for marine species
  let corrected = obs;
  if (/whale|dolphin|orca|porpoise/.test(n)) corrected = obs / 4;
  else if (/shark/.test(n)) corrected = obs / 2;
  if (corrected >= 2000) return 'guaranteed';
  if (corrected >= 500)  return 'very_likely';
  if (corrected >= 100)  return 'likely';
  if (corrected >= 20)   return 'unlikely';
  if (corrected >= 5)    return 'rare';
  return 'exceptional';
}

async function task2_marineAudit(cache) {
  console.log('\n══════════════════════════════════════════════════');
  console.log('  TASK 2 — Marine life completeness audit');
  console.log('══════════════════════════════════════════════════\n');

  const toAdd = []; // { park, animal }

  for (const { id, name } of MARINE_PARKS) {
    const placeId = INAT_PLACE_IDS[id];
    if (!placeId) { console.log(`  ⚠ No place_id for ${id}`); continue; }

    console.log(`\n── ${name} (place_id=${placeId}) ──`);
    const existing = new Set(
      (cache[id]?.animals || []).map(a => a.name.toLowerCase())
    );

    const topMarine = await fetchTopMarineForPark(placeId);
    if (!topMarine.length) { console.log('  (no results)'); continue; }

    let added = 0, already = 0;
    for (const sp of topMarine) {
      if (existing.has(sp.name.toLowerCase())) {
        console.log(`  ✓ already: ${sp.name} (${sp.obs} obs)`);
        already++;
      } else {
        const rarity = rarityFromObs(sp.obs, sp.name);
        console.log(`  + MISSING: ${sp.name} (${sp.obs} obs → ${rarity})`);
        toAdd.push({
          park: id,
          animal: {
            name:           sp.name,
            emoji:          '🐟',
            animalType:     'marine',
            rarity,
            seasons:        ['spring', 'summer', 'fall'],
            scientificName: sp.sciName || null,
            funFact:        `${sp.name} is documented in ${name} with ${sp.obs} iNaturalist research-grade observations.`,
            photoUrl:       null,
            source:         'inaturalist',
            sources:        ['inaturalist'],
            description:    null,
            descriptionSource: null,
          },
        });
        added++;
      }
    }
    console.log(`  → ${already} already present, ${added} gaps found`);
  }

  // Fetch photos+descriptions for new marine animals
  if (toAdd.length > 0) {
    console.log(`\nFetching taxon data for ${toAdd.length} missing marine species…`);
    const seen = new Set();
    for (const { park, animal } of toAdd) {
      const key = animal.sciName || animal.name;
      if (!seen.has(key)) {
        seen.add(key);
        process.stdout.write(`  ${animal.name}… `);
        const t = await fetchTaxon(animal.name, animal.sciName);
        if (t) {
          if (t.photoUrl) animal.photoUrl = t.photoUrl;
          if (t.description) {
            animal.description = t.description;
            animal.descriptionSource = 'Wikipedia';
          }
          console.log(`✓ photo=${!!t.photoUrl} desc=${!!t.description}`);
        } else {
          console.log('⚠ no taxon data');
        }
      }
    }

    // Add to cache
    if (!DRY_RUN) {
      for (const { park, animal } of toAdd) {
        if (!cache[park]) continue;
        const exists = cache[park].animals.some(a => a.name.toLowerCase() === animal.name.toLowerCase());
        if (!exists) {
          cache[park].animals.push(animal);
        }
      }
      console.log(`\n  ✓ Added ${toAdd.length} missing marine species to cache`);
    } else {
      console.log(`\n  DRY_RUN: would add ${toAdd.length} missing marine species`);
    }
  } else {
    console.log('\n  ✓ No missing marine species found!');
  }

  return toAdd.length;
}

// ═══════════════════════════════════════════════════════════════════════════
// TASK 3 — Fix missing descriptions
// ═══════════════════════════════════════════════════════════════════════════

const PLACEHOLDER_RE = [
  /^\d+ research-grade iNaturalist observations at this park\.?$/i,
  /^Recorded \d+ times on iNaturalist at this park\.?$/i,
  /^Appears on \d+% of .+ eBird checklists/i,
  /^Officially documented in the NPS wildlife registry/i,
  /^Recently reported within/i,
  /^Listed in the NPS species inventory/i,
  /^Confirmed at this park's eBird hotspot\.?$/i,
  /^Recorded in this region \(eBird historical checklist\)\.?$/i,
  /^is a (mammal|bird|reptile|amphibian|fish|insect|marine) found at .+ National Park\. It is/i,
];

function isPlaceholder(text) {
  if (!text?.trim()) return true;
  return PLACEHOLDER_RE.some(re => re.test(text.trim()));
}

function needsDesc(animal) {
  if (animal.description && !isPlaceholder(animal.description)) return false;
  if (animal.funFact && !isPlaceholder(animal.funFact)) return false;
  return true;
}

async function task3_fixDescriptions(cache) {
  console.log('\n══════════════════════════════════════════════════');
  console.log('  TASK 3 — Fix missing descriptions');
  console.log('══════════════════════════════════════════════════\n');

  // Collect all animals needing descriptions (dedupe by name+sciName)
  const needDesc = new Map(); // key → { name, sciName, locations: [] }
  for (const [parkId, parkData] of Object.entries(cache)) {
    for (const animal of parkData.animals || []) {
      if (!needsDesc(animal)) continue;
      const key = (animal.scientificName || animal.name).toLowerCase();
      if (!needDesc.has(key)) {
        needDesc.set(key, { name: animal.name, sciName: animal.scientificName, locations: [] });
      }
      needDesc.get(key).locations.push({ parkId, animal });
    }
  }

  console.log(`Animals needing descriptions: ${needDesc.size}`);
  if (needDesc.size === 0) { console.log('  ✓ All animals have descriptions!'); return 0; }

  // List the first 30
  let listed = 0;
  for (const [, info] of needDesc) {
    if (listed++ >= 30) { console.log(`  … and ${needDesc.size - 30} more`); break; }
    console.log(`  - ${info.name} (${info.sciName || 'no sci name'}) @ ${info.locations.length} park(s)`);
  }

  // Fetch Wikipedia descriptions
  console.log(`\nFetching Wikipedia descriptions for ${needDesc.size} species…`);
  let wikiFound = 0, fallback = 0;

  for (const [key, info] of needDesc) {
    process.stdout.write(`  ${info.name}… `);
    const t = await fetchTaxon(info.name, info.sciName);

    let description = null;
    let descriptionSource = null;

    if (t?.description) {
      description = t.description;
      descriptionSource = 'Wikipedia';
      wikiFound++;
      console.log('✓ Wikipedia');
    } else {
      // Build factual template description from the animal name + locations
      const parkNames = [...new Set(info.locations.map(l => l.parkId))].slice(0, 3).join(', ');
      description = `${info.name} is a ${info.locations[0]?.animal?.animalType || 'wildlife'} species documented in US national parks including ${parkNames}.`;
      descriptionSource = 'Park Records';
      fallback++;
      console.log('→ template');
    }

    // Apply to all instances in cache
    for (const { animal } of info.locations) {
      if (!animal.description || isPlaceholder(animal.description)) {
        animal.description = description;
        animal.descriptionSource = descriptionSource;
      }
      // Also update photoUrl if we got one and it was missing
      if (t?.photoUrl && !animal.photoUrl) {
        animal.photoUrl = t.photoUrl;
      }
    }
  }

  console.log(`\nDescription enrichment:`);
  console.log(`  Wikipedia descriptions: ${wikiFound}`);
  console.log(`  Template fallbacks:     ${fallback}`);
  console.log(`  Total fixed:            ${wikiFound + fallback}`);

  return wikiFound + fallback;
}

// ═══════════════════════════════════════════════════════════════════════════
// TASK 4 — Rarity audit on key parks
// ═══════════════════════════════════════════════════════════════════════════
function task4_rarityAudit(cache) {
  console.log('\n══════════════════════════════════════════════════');
  console.log('  TASK 4 — Rarity audit on key parks');
  console.log('══════════════════════════════════════════════════\n');

  // Check Saguaro reptiles — Desert Spiny Lizard should appear early
  const saguaroReptiles = (cache.saguaro?.animals || [])
    .filter(a => a.animalType === 'reptile')
    .sort((a,b) => {
      const ord = ['guaranteed','very_likely','likely','unlikely','rare','exceptional'];
      return ord.indexOf(a.rarity) - ord.indexOf(b.rarity);
    });
  console.log('Saguaro reptiles (sorted by rarity):');
  saguaroReptiles.slice(0, 8).forEach((a, i) => console.log(`  ${i+1}. ${a.name} [${a.rarity}]`));

  // Check Glacier mammals
  const glacierMammals = (cache.glacier?.animals || []).filter(a => a.animalType === 'mammal');
  console.log('\nGlacier mammals:');
  glacierMammals.forEach(a => console.log(`  • ${a.name} [${a.rarity}]`));

  // Zion Desert Bighorn Sheep
  const zionBighorn = cache.zion?.animals?.find(a => a.name === 'Desert Bighorn Sheep');
  console.log(`\nZion / Desert Bighorn Sheep: ${zionBighorn?.rarity || 'MISSING'} ${zionBighorn ? '✅' : '❌'}`);

  // Grand Canyon Elk
  const gcElk = cache.grandcanyon?.animals?.find(a => a.name === 'Elk');
  console.log(`Grand Canyon / Elk: ${gcElk?.rarity || 'MISSING'} ${gcElk?.rarity === 'likely' ? '✅' : '❌'}`);
}

// ═══════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════
async function main() {
  console.log('══════════════════════════════════════════════════');
  console.log('  Wildlife Map — Follow-Up Audit');
  console.log('══════════════════════════════════════════════════');

  const { cache, builtAt } = loadCache();
  const initialCount = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0);

  await task1_verifyNewAnimals(cache);
  task4_rarityAudit(cache);

  let marineAdded = 0;
  if (!SKIP_MARINE) {
    marineAdded = await task2_marineAudit(cache);
  } else {
    console.log('\n[Skipping TASK 2 — marine audit (SKIP_MARINE=1)]');
  }

  let descFixed = 0;
  if (!SKIP_DESC) {
    descFixed = await task3_fixDescriptions(cache);
  } else {
    console.log('\n[Skipping TASK 3 — descriptions (SKIP_DESC=1)]');
  }

  // Save
  if (!DRY_RUN && (marineAdded > 0 || descFixed > 0)) {
    console.log('\nWriting updated wildlifeCache.js…');
    saveCache(cache, builtAt);
    const finalCount = Object.values(cache).reduce((s,p)=>s+(p.animals||[]).length,0);
    console.log(`  ✓ Written: ${finalCount} total animals (was ${initialCount})`);
  } else if (DRY_RUN) {
    console.log('\nDRY_RUN — no changes written');
  } else {
    console.log('\nNo cache changes needed — nothing to write');
  }

  console.log('\n══════════════════════════════════════════════════');
  console.log('  AUDIT COMPLETE');
  console.log(`  Marine species added:      ${marineAdded}`);
  console.log(`  Descriptions fixed:        ${descFixed}`);
  console.log('══════════════════════════════════════════════════');
}

main().catch(err => { console.error('Audit script failed:', err); process.exit(1); });
