#!/usr/bin/env node
/**
 * scripts/mergeShards.js
 *
 * Reads partial cache JSONs produced by sharded `buildWildlifeCache.js` runs
 * (PARTIAL_OUT mode) and merges them into a single src/data/wildlifeCache.js.
 *
 * Why: GitHub Actions caps standard runners at 6h per job, but a full rebuild
 * takes longer than that. The weekly workflow now fans out the rebuild across
 * a matrix of N shards (each runner gets its own 6h budget); this merge step
 * stitches the partial outputs back together.
 *
 * Behaviour:
 *   - Starts from the existing main-branch wildlifeCache.js so any park NOT
 *     covered by an incoming shard is preserved verbatim. Defensive: if a
 *     shard is missing, we ship stale data for those parks instead of
 *     dropping them.
 *   - Iterates every JSON file in the shard directory and overlays its
 *     parks on top of the base cache. Later shards overwrite earlier ones
 *     for the same park id (shouldn't happen with stride sharding, but is
 *     deterministic if it does).
 *   - Picks the latest `builtAt` across all shards for the file header.
 *
 * Usage:
 *   node scripts/mergeShards.js <shards-dir>
 *   node scripts/mergeShards.js shards/      # default
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

async function main() {
  const shardsDir = process.argv[2]
    ? path.resolve(process.argv[2])
    : path.join(ROOT, 'shards');

  if (!existsSync(shardsDir)) {
    throw new Error(`Shards directory not found: ${shardsDir}`);
  }

  console.log(`🧩 Merging shard caches from ${shardsDir}…\n`);

  // Seed from the existing main-branch cache so unrebuilt parks aren't dropped.
  let base = {};
  try {
    const existing = await import('../src/data/wildlifeCache.js');
    base = { ...(existing.WILDLIFE_CACHE ?? {}) };
    console.log(`   Base cache: ${Object.keys(base).length} parks (from src/data/wildlifeCache.js)`);
  } catch {
    console.log('   Base cache: empty (no existing wildlifeCache.js)');
  }

  // Find shard files
  const shardFiles = readdirSync(shardsDir)
    .filter(f => f.endsWith('.json'))
    .sort();

  if (shardFiles.length === 0) {
    throw new Error(`No shard JSONs found in ${shardsDir}`);
  }

  console.log(`   Shards:     ${shardFiles.length}\n`);

  let latestBuiltAt = null;
  let totalRebuiltParks = 0;

  for (const file of shardFiles) {
    const fullPath = path.join(shardsDir, file);
    const data = JSON.parse(readFileSync(fullPath, 'utf8'));
    const ids = Object.keys(data);
    console.log(`   ▸ ${file}: ${ids.length} parks → ${ids.join(', ')}`);
    for (const [id, val] of Object.entries(data)) {
      base[id] = val;
      if (val.builtAt && (!latestBuiltAt || val.builtAt > latestBuiltAt)) {
        latestBuiltAt = val.builtAt;
      }
    }
    totalRebuiltParks += ids.length;
  }

  const builtAt = latestBuiltAt ?? new Date().toISOString();
  const totalSpecies = Object.values(base).reduce((s, v) => s + (v.animals?.length ?? 0), 0);

  // Reuse the same emitter shape the build script uses so downstream tools
  // (splitCache, etc.) see an identical file structure.
  const lines = [
    `// Auto-generated by scripts/mergeShards.js — do not edit manually.`,
    `// Built: ${builtAt}`,
    `// Parks: ${Object.keys(base).length} | Species bundled: ${totalSpecies}`,
    `// Merged from ${shardFiles.length} shard(s).`,
    ``,
    `export const WILDLIFE_CACHE_BUILT_AT = ${JSON.stringify(builtAt)};`,
    ``,
    `export const WILDLIFE_CACHE = {`,
  ];

  for (const [id, val] of Object.entries(base)) {
    lines.push(`  ${JSON.stringify(id)}: {`);
    lines.push(`    builtAt: ${JSON.stringify(val.builtAt)},`);
    lines.push(`    animals: ${JSON.stringify(val.animals, null, 2).replace(/\n/g, '\n    ')},`);
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push(``);

  const outPath = path.join(ROOT, 'src', 'data', 'wildlifeCache.js');
  writeFileSync(outPath, lines.join('\n'), 'utf8');

  console.log(`\n✅  Merged ${totalRebuiltParks} rebuilt park(s) into ${Object.keys(base).length} total → ${outPath}`);
  console.log(`   Species: ${totalSpecies}`);
  console.log(`   Built:   ${builtAt}\n`);
}

main().catch(err => {
  console.error('Merge failed:', err);
  process.exit(1);
});
