#!/usr/bin/env node
/**
 * scripts/patchSourcesCache.mjs
 *
 * Patches the existing wildlifeCache.js to set correct source/sources fields
 * on every animal based on its funFact text.
 *
 * Background: wildlifeCache.js was built before the fetch functions tagged
 * their animals with source fields, so every animal has source:"static".
 * The funFact text is the only reliable indicator of which API produced
 * each entry (buildWildlifeCache.js uses distinct templates per API).
 *
 * This script does NOT reconstruct multi-source arrays — that requires a
 * full rebuild with the fixed dedup() function (node buildWildlifeCache.js).
 * It does correctly set the PRIMARY source for all ~35,000 animals.
 *
 * Usage:  node scripts/patchSourcesCache.mjs
 */

import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH  = path.join(__dirname, '../src/data/wildlifeCache.js');

// ── Source inference (mirrors App.jsx resolveAnimalSources) ──────────────────
function inferSource(fact) {
  if (!fact) return 'static';
  if (/iNaturalist/i.test(fact))            return 'inaturalist';
  if (/eBird/i.test(fact))                  return 'ebird';
  if (/NPS wildlife registry/i.test(fact))  return 'nps';
  return 'static'; // genuine hardcoded / park record
}

// ── Load existing cache ───────────────────────────────────────────────────────
console.log('Loading wildlifeCache.js …');
const { WILDLIFE_CACHE, WILDLIFE_CACHE_BUILT_AT } = await import('../src/data/wildlifeCache.js');

// ── Patch each animal ─────────────────────────────────────────────────────────
let totalAnimals = 0;
let patched      = 0;
let bySource     = { ebird: 0, inaturalist: 0, nps: 0, static: 0 };

const patchedCache = {};

for (const [parkId, parkData] of Object.entries(WILDLIFE_CACHE)) {
  const animals = (parkData.animals ?? []).map(a => {
    totalAnimals++;
    const src = inferSource(a.funFact);
    if (src !== (a.source ?? 'static')) patched++;
    bySource[src] = (bySource[src] ?? 0) + 1;
    return { ...a, source: src, sources: [src] };
  });
  patchedCache[parkId] = { ...parkData, animals };
}

// ── Write output ──────────────────────────────────────────────────────────────
const totalSpecies = Object.values(patchedCache).reduce((s, v) => s + v.animals.length, 0);

const lines = [
  `// Auto-generated by scripts/buildWildlifeCache.js — do not edit manually.`,
  `// Built: ${WILDLIFE_CACHE_BUILT_AT}`,
  `// Parks: ${Object.keys(patchedCache).length} | Species bundled: ${totalSpecies}`,
  `// To regenerate: node scripts/buildWildlifeCache.js`,
  ``,
  `export const WILDLIFE_CACHE_BUILT_AT = ${JSON.stringify(WILDLIFE_CACHE_BUILT_AT)};`,
  ``,
  `export const WILDLIFE_CACHE = {`,
];

for (const [id, val] of Object.entries(patchedCache)) {
  lines.push(`  ${JSON.stringify(id)}: {`);
  lines.push(`    builtAt: ${JSON.stringify(val.builtAt)},`);
  lines.push(`    animals: ${JSON.stringify(val.animals, null, 2).replace(/\n/g, '\n    ')},`);
  lines.push(`  },`);
}
lines.push(`};`);
lines.push(``);

writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');

// ── Report ─────────────────────────────────────────────────────────────────────
console.log(`\n✅  Patched ${OUT_PATH}`);
console.log(`   Total animals : ${totalAnimals.toLocaleString()}`);
console.log(`   Source updated: ${patched.toLocaleString()} (${Math.round(patched/totalAnimals*100)}%)`);
console.log(`\n   Source breakdown:`);
console.log(`     🐦 eBird          : ${(bySource.ebird       ?? 0).toLocaleString()}`);
console.log(`     🌿 iNaturalist    : ${(bySource.inaturalist ?? 0).toLocaleString()}`);
console.log(`     🏛️  NPS            : ${(bySource.nps         ?? 0).toLocaleString()}`);
console.log(`     📌 Park Records   : ${(bySource.static      ?? 0).toLocaleString()}`);
console.log(`\n   Note: multi-source arrays (sources: ['ebird','inaturalist'])`);
console.log(`   require a full rebuild: node scripts/buildWildlifeCache.js`);
console.log(`   Live data already produces multi-source via deduplicateAnimals().\n`);
