#!/usr/bin/env node
/**
 * scripts/splitBirdFreq.mjs — split the monolithic county bird-frequency
 * dataset into per-state lazy chunks.
 *
 * Why: stateParkBirdFreq.js is ~12MB (1.3MB gzip). As a single lazy chunk,
 * opening ONE state park downloaded the bird data for ALL 50 states — brutal
 * on a phone connection. Split per state, a park-open fetches ~25KB instead
 * (the state's parks + only the counties those parks reference).
 *
 * Partitioning is by PARK ID prefix (xx-). A county referenced by parks in
 * two states (border parks) is duplicated into both chunks — a few KB of
 * overlap for zero correctness risk.
 *
 * Run AFTER buildStateParkBirdFreq.js (which writes the monolith — kept in
 * the repo as the source of truth; the app no longer imports it, so it is
 * NOT bundled):  node scripts/splitBirdFreq.mjs
 *
 * Output: src/data/birdFreq/freq_<xx>.js × 50 (consumed via loader.js).
 */
import { writeFileSync, mkdirSync } from 'fs';
import { PARK_COUNTY, COUNTY_BIRD_FREQ } from '../src/data/stateParkBirdFreq.js';
import { UNIT_COUNTY } from '../src/data/unitCounty.js';
import { UNIT_COUNTY_EXTRA } from '../src/data/unitCountyExtra.js';

// Counties referenced by FEDERAL units (nwr_* / nps_*), grouped by the state in
// the county code itself. useLiveData resolves a unit's chunk with
// `county.split('-')[1]`, so a refuge county MUST live in the chunk matching its
// own code — not the refuge's stateCodes, which can differ on a border.
//
// Without this the widened build was pointless: partitioning keys off the park
// id prefix (`xx-`), and federal ids don't match any state, so every
// federal-only county was sampled and then silently dropped here.
const UNIT_COUNTIES_BY_STATE = {};
for (const c of new Set([...Object.values(UNIT_COUNTY), ...Object.values(UNIT_COUNTY_EXTRA)])) {
  const st = String(c || '').split('-')[1]?.toLowerCase();
  if (!st) continue;
  (UNIT_COUNTIES_BY_STATE[st] ??= new Set()).add(c);
}

const STATES = ['al','ak','az','ar','ca','co','ct','de','fl','ga','hi','id','il','in','ia','ks','ky','la','me','md','ma','mi','mn','ms','mo','mt','ne','nv','nh','nj','nm','ny','nc','nd','oh','ok','or','pa','ri','sc','sd','tn','tx','ut','vt','va','wa','wv','wi','wy',
  // Puerto Rico: no state parks, but 5 NWRs sit in US-PR-### municipios.
  // eBird treats PR as a subnational1 with municipio subnational2 codes.
  'pr'];

mkdirSync(new URL('../src/data/birdFreq/', import.meta.url), { recursive: true });

let totalParks = 0, totalCounties = 0;
for (const st of STATES) {
  const parkCounty = {};
  const counties = new Set();
  for (const [pid, county] of Object.entries(PARK_COUNTY)) {
    if (!pid.startsWith(`${st}-`)) continue;
    parkCounty[pid] = county;
    counties.add(county);
  }
  for (const c of UNIT_COUNTIES_BY_STATE[st] ?? []) counties.add(c);
  const countyFreq = {};
  for (const c of counties) if (COUNTY_BIRD_FREQ[c]) countyFreq[c] = COUNTY_BIRD_FREQ[c];
  totalParks += Object.keys(parkCounty).length;
  totalCounties += Object.keys(countyFreq).length;
  const body =
`// Auto-generated by scripts/splitBirdFreq.mjs — do not edit.
// ${st.toUpperCase()}: ${Object.keys(parkCounty).length} parks, ${Object.keys(countyFreq).length} counties.
export const PARK_COUNTY = ${JSON.stringify(parkCounty)};
export const COUNTY_BIRD_FREQ = ${JSON.stringify(countyFreq)};
`;
  writeFileSync(new URL(`../src/data/birdFreq/freq_${st}.js`, import.meta.url), body);
}
console.log(`Split ${totalParks} parks / ${totalCounties} county entries (incl. border duplicates) into ${STATES.length} state chunks.`);
