// ── Rarity tiers — based on likelihood of seeing on a typical visit ────────────
// Thresholds match rarityFromChecklist() / rarityFromObsCount() in apiService.js:
//   guaranteed  > 90%   — you will almost certainly see this on any visit
//   very_likely 60-90%  — you will probably see this with a little looking
//   likely      30-60%  — good chance if you spend a full day
//   unlikely    10-30%  — possible but not expected on a typical visit
//   rare         2-10%  — a lucky sighting, worth reporting
//   exceptional  < 2%   — once in a season or lifetime
// Sequential rarity ramp — one hue family (green → gold → clay → plum) shifted
// in lightness/chroma so tier differences read as a gradient, not six competing
// signals. Rarity is the only attribute that gets saturated color in the UI.
export const RARITY = {
  all:         { label: 'All',          emoji: '',    color: '#6b7280', subLabel: '',                     probability: '',       star: false },
  guaranteed:  { label: 'Guaranteed',   emoji: '🟢', color: '#1a6640', subLabel: 'Almost certain to see', probability: '90%+',   star: false },
  very_likely: { label: 'Very Likely',  emoji: '🟩', color: '#4a8557', subLabel: 'Probably will see',     probability: '60-90%', star: false },
  likely:      { label: 'Likely',       emoji: '🟡', color: '#8a7a3e', subLabel: 'Good chance',           probability: '30-60%', star: false },
  unlikely:    { label: 'Unlikely',     emoji: '🟠', color: '#a06a44', subLabel: 'Possible with luck',    probability: '10-30%', star: false },
  rare:        { label: 'Rare',         emoji: '🔴', color: '#9a5248', subLabel: 'Lucky sighting',        probability: '2-10%',  star: false },
  exceptional: { label: 'Exceptional',  emoji: '⭐', color: '#7a4e6e', subLabel: 'Once in a lifetime',    probability: '<2%',    star: true  },
};

// ── Seasons ───────────────────────────────────────────────────────────────────
// Subtle seasonal tint — enough personality to cue the season at a glance
// without competing with the rarity ramp for attention.
export const SEASONS = {
  all:    { label: 'All Seasons', emoji: '',    color: '#6b7280' },
  spring: { label: 'Spring',      emoji: '🌸', color: '#ec9ab9' },
  summer: { label: 'Summer',      emoji: '☀️', color: '#d49232' },
  fall:   { label: 'Fall',        emoji: '🍂', color: '#b5611e' },
  winter: { label: 'Winter',      emoji: '❄️', color: '#5ba0c8' },
};

// ── Animal types ──────────────────────────────────────────────────────────────
export const ANIMAL_TYPES = {
  all:       { label: 'All Types',   emoji: '🐾', color: '#6b7280' },
  bird:      { label: 'Birds',       emoji: '🐦', color: '#0891b2' },
  mammal:    { label: 'Mammals',     emoji: '🦌', color: '#7c3aed' },
  reptile:   { label: 'Reptiles',    emoji: '🐊', color: '#15803d' },
  amphibian: { label: 'Amphibians',  emoji: '🐸', color: '#65a30d' },
  insect:    { label: 'Insects',     emoji: '🦋', color: '#d97706' },
  marine:    { label: 'Marine Life', emoji: '🐋', color: '#1d4ed8' },
};

// ── Location types ────────────────────────────────────────────────────────────
export const LOCATION_TYPES = {
  nationalPark: { label: 'National Park', emoji: '🏔️', color: '#7B5B2E' },
};

// ── US state codes → names ────────────────────────────────────────────────────
export const STATE_NAMES = {
  AK: 'Alaska', AL: 'Alabama', AR: 'Arkansas', AZ: 'Arizona', CA: 'California',
  CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware', FL: 'Florida',
  GA: 'Georgia', HI: 'Hawaii', ID: 'Idaho', IL: 'Illinois',
  IN: 'Indiana', KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana',
  MA: 'Massachusetts', MD: 'Maryland', ME: 'Maine', MI: 'Michigan',
  MN: 'Minnesota', MO: 'Missouri', MT: 'Montana', NC: 'North Carolina',
  ND: 'North Dakota', NE: 'Nebraska', NH: 'New Hampshire', NJ: 'New Jersey',
  NM: 'New Mexico', NV: 'Nevada', NY: 'New York', OH: 'Ohio',
  OK: 'Oklahoma', OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island',
  SC: 'South Carolina', SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas',
  UT: 'Utah', VA: 'Virginia', VT: 'Vermont', WA: 'Washington',
  WI: 'Wisconsin', WV: 'West Virginia', WY: 'Wyoming',
  // Territories
  AS: 'American Samoa', GU: 'Guam', VI: 'US Virgin Islands',
};

// ── Location data ─────────────────────────────────────────────────────────────
// Each location: { id, name, state, stateCodes[], lat, lng, emoji,
//                  locationType, npsCode?, animals[] }
// Each animal:   { name, emoji, animalType, seasons[], bestSeason,
//                  rarity, funFact, source? }

export const wildlifeLocations = [

  // ══════════════════════════════════════════════════════════════════════════
  // NATIONAL PARKS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'yellowstone',
    name: 'Yellowstone National Park',
    state: 'Wyoming / Montana / Idaho',
    stateCodes: ['WY', 'MT', 'ID'],
    lat: 44.428, lng: -110.588,
    emoji: '🦬',
    locationType: 'nationalPark',
    npsCode: 'yell',
    animals: [
      { name: 'American Bison', emoji: '🦬', animalType: 'mammal',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'guaranteed',
        funFact: "Yellowstone's herd of 5,500+ bison is the largest wild population in the US. Spring calves are called 'red dogs' for their rusty orange color." },
      { name: 'Gray Wolf', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis lupus',
        seasons: ['year_round'], bestSeason: 'winter', rarity: 'rare',
        migrationStatus: 'year_round',
        funFact: "Reintroduced in 1995 after a 70-year absence, wolves triggered a 'trophic cascade' so powerful it changed the shape of Yellowstone's rivers by altering elk grazing patterns." },
      { name: 'Wolverine', emoji: '🦡', animalType: 'mammal',
        scientificName: 'Gulo gulo',
        seasons: ['winter'], bestSeason: 'winter', rarity: 'exceptional',
        funFact: "Fewer than 300 wolverines remain in the contiguous US. They travel 15+ miles daily through deep snow and have driven grizzly bears from kills." },
      { name: 'Mountain Lion', emoji: '🐆', animalType: 'mammal',
        scientificName: 'Puma concolor',
        seasons: ['spring', 'summer', 'fall', 'winter'], rarity: 'exceptional',
        funFact: "Officially documented in the NPS wildlife registry for Yellowstone National Park. Solitary and highly secretive, mountain lions are almost never seen despite a resident population in the park." },
      { name: 'Grizzly Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos horribilis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Yellowstone hosts about 150 grizzlies. Spring is peak viewing — bears emerge from dens in March and congregate at Lamar Valley's carcasses and early-greening meadows, sometimes visible from the road." },
      { name: 'American Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'guaranteed',
        funFact: "The Lamar and Hayden valleys hold thousands of elk. In September, the bugling rut fills the valleys with sound — bulls collect harems while wolves and bears watch from a distance." },
      { name: 'Pronghorn', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Antilocapra americana',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Pronghorn are the second-fastest land animal on earth (55 mph) and the fastest in the western hemisphere. Yellowstone's population migrates 100+ miles to winter range — one of the longest land migrations in the lower 48." },
      { name: 'Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Rocky Mountain bighorn sheep frequent the steep terrain around Yellowstone's Northern Range. The rams' dramatic head-butting clashes in November — audible from a half mile away — are among the park's most memorable wildlife moments." },
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['spring', 'fall', 'winter'], bestSeason: 'winter', rarity: 'unlikely',
        funFact: "Bald eagles overwinter along Yellowstone's rivers in large numbers, feeding on fish and bison carcasses. The Yellowstone River corridor holds one of the highest concentrations of wintering bald eagles in the Rocky Mountains." },
      { name: 'Sandhill Crane', emoji: '🐦', animalType: 'bird',
        scientificName: 'Antigone canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Greater sandhill cranes nest in Yellowstone's meadows and are a regular sight in Hayden Valley. Their bugling calls, carrying over a mile, are one of the most evocative sounds in the park." },
    ],
  },

  {
    id: 'everglades',
    name: 'Everglades National Park',
    state: 'Florida',
    stateCodes: ['FL'],
    lat: 25.286, lng: -80.899,
    emoji: '🐊',
    locationType: 'nationalPark',
    npsCode: 'ever',
    animals: [
      { name: 'American Alligator', emoji: '🐊', animalType: 'reptile',
        seasons: ['winter', 'spring'], bestSeason: 'winter', rarity: 'guaranteed',
        funFact: "In dry season, hundreds of alligators congregate at shrinking water holes. Their wallowing creates pools that sustain dozens of other species — making them a keystone species." },
      { name: 'Roseate Spoonbill', emoji: '🦩', animalType: 'bird',
        seasons: ['winter', 'spring'], bestSeason: 'winter', rarity: 'unlikely',
        funFact: "Spoonbills get their brilliant pink color entirely from the crustaceans they eat — captive birds fed plain fish turn white. They sweep their spatula bill side-to-side to feel for prey." },
      { name: 'Florida Panther', emoji: '🐆', animalType: 'mammal',
        scientificName: 'Puma concolor coryi',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'exceptional',
        funFact: "Fewer than 200 Florida Panthers survive in the wild. A sighting is so extraordinary that biologists still track each confirmed encounter individually." },
      { name: 'American Crocodile', emoji: '🐊', animalType: 'reptile',
        scientificName: 'Crocodylus acutus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'rare',
        funFact: "The Everglades is the only place on earth where alligators and crocodiles coexist. American crocodiles prefer the saltier water of Florida Bay; they're shy and retiring compared to the far more aggressive American alligator." },
      { name: 'West Indian Manatee', emoji: '🦭', animalType: 'marine',
        scientificName: 'Trichechus manatus',
        seasons: ['winter', 'spring'], bestSeason: 'winter', rarity: 'unlikely',
        funFact: "Manatees congregate in Everglades waterways during winter, seeking the warmer waters of springs and coastal areas. Gentle and slow-moving, they are vulnerable to boat strikes — their backs are often marked with propeller scars." },
      { name: 'Anhinga', emoji: '🐦', animalType: 'bird',
        scientificName: 'Anhinga anhinga',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'likely',
        funFact: "Unlike ducks, anhingas lack waterproofing oil on their feathers, so they sink efficiently to hunt fish underwater. After diving, they must stand with wings outstretched in the sun to dry — a distinctive pose visible along every Everglades waterway." },
      { name: 'Wood Stork', emoji: '🐦', animalType: 'bird',
        scientificName: 'Mycteria americana',
        seasons: ['winter', 'spring'], bestSeason: 'winter', rarity: 'unlikely',
        funFact: "The wood stork is the only stork native to North America. It feeds by touch, not sight — sweeping its bill through shallow water and snapping it shut in 25 milliseconds when it contacts a fish. Breeding success is directly tied to water levels." },
    ],
  },

  {
    id: 'denali',
    name: 'Denali National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 63.115, lng: -151.193,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'dena',
    animals: [
      { name: 'Caribou', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Rangifer tarandus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Denali's caribou herd numbers around 2,000 animals. Both males and females grow antlers — the only deer species where females are antlered. They migrate across the park each summer, visible from the single park road." },
      { name: 'Brown Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Denali hosts roughly 300 brown bears that roam across an average home range of 500–1,000 square miles. In July, bears congregate on open tundra to dig ground squirrels and feast on soapberries before the fall hyperphagia." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Denali's Alaska moose are the largest subspecies on earth — bulls can exceed 1,600 lbs and carry antlers spanning 6 feet. The Nenana River corridor near the park entrance is prime moose habitat all year." },
      { name: 'Dall Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis dalli',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Bright white Dall sheep are among the most reliably seen large mammals in Denali, grazing the high alpine ridges visible from the park road. Ewes and lambs congregate in summer on steep cliffs safe from wolves and bears." },
      { name: 'Gray Wolf', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis lupus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'rare',
        funFact: "Denali is one of the best places in the world to observe wild wolf behavior. About 80–100 wolves live in the park in roughly 8 packs. The Toklat pack, studied since 1986, is one of the most scientifically documented wolf families on earth." },
      { name: 'Arctic Ground Squirrel', emoji: '🐿️', animalType: 'mammal',
        scientificName: 'Urocitellus parryii',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "Arctic ground squirrels are the most cold-tolerant hibernating mammal — their body temperature drops below freezing during winter sleep. They are the primary prey of Denali's bears, wolves, foxes, and raptors." },
      { name: 'Willow Ptarmigan', emoji: '🐦', animalType: 'bird',
        scientificName: 'Lagopus lagopus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'likely',
        funFact: "Alaska's state bird, the willow ptarmigan, turns completely white in winter — even its feet grow feathers for insulation. In spring, the male's brilliant russet head contrasts against its white body. Flocks of hundreds cross the tundra in fall." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NORTHEAST NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'acadia',
    name: 'Acadia National Park',
    state: 'Maine',
    stateCodes: ['ME'],
    lat: 44.35691656, lng: -68.9547165,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'acad',
    animals: [
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['year_round'], bestSeason: 'summer', rarity: 'rare',
        migrationStatus: 'year_round',
        funFact: "Acadia hosts a significant population of nesting bald eagles. The park's rugged coastline and numerous lakes provide ideal hunting habitat — look for them soaring over Eagle Lake and Jordan Pond." },
      { name: 'Harbor Seal', emoji: '🦭', animalType: 'marine',
        scientificName: 'Phoca vitulina',
        seasons: ['year_round'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Harbor seals haul out on Acadia's offshore ledges by the hundreds. They're most visible at low tide from the Bass Harbor Head Lighthouse area and on ledges off Schoodic Peninsula." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'rare',
        funFact: "Moose occasionally wander into Acadia from adjacent wild lands. Spring is the best time — look for them in boggy areas and along pond edges at dawn, where they wade belly-deep to feed on aquatic vegetation." },
      { name: 'Common Loon', emoji: '🐦', animalType: 'bird',
        scientificName: 'Gavia immer',
        seasons: ['year_round'], bestSeason: 'summer', rarity: 'likely',
        migrationStatus: 'year_round',
        funFact: "Common loons nest on Acadia's freshwater ponds, raising chicks that often ride on their parents' backs for the first weeks of life. Their haunting wail echoing over Eagle Lake at dusk is one of the park's most iconic sounds." },
      { name: 'Peregrine Falcon', emoji: '🦅', animalType: 'bird',
        scientificName: 'Falco peregrinus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        migrationStatus: 'partial',
        funFact: "Peregrine falcons were reintroduced to Acadia's cliffs after extirpation by DDT. They now breed on the granite sea cliffs — Precipice Trail is often closed during nesting season to protect them." },
      { name: 'Atlantic Puffin', emoji: '🐦', animalType: 'bird',
        scientificName: 'Fratercula arctica',
        seasons: ['spring', 'summer'], bestSeason: 'summer', rarity: 'rare',
        migrationStatus: 'partial',
        funFact: "Atlantic puffins can be seen offshore near Acadia during summer, though their nesting colonies are on Maine's offshore islands (especially Seal Island and Matinicus Rock). Boat tours from Bar Harbor offer good views." },
      { name: 'White-tailed Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus virginianus',
        seasons: ['year_round'], bestSeason: 'fall', rarity: 'likely',
        funFact: "White-tailed deer are abundant throughout Acadia's forests and open areas. In fall, bucks are frequently spotted near the carriage roads at dawn, their necks swollen with the rut." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Black bears are regular if rarely-seen residents of Acadia's forested interior. They're most active at dawn and dusk along the park's back roads, particularly during blueberry season in late summer." },
    ],
  },

  {
    id: 'shenandoah',
    name: 'Shenandoah National Park',
    state: 'Virginia',
    stateCodes: ['VA'],
    lat: 38.4937, lng: -78.4697,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'shen',
    animals: [
      { name: 'White-tailed Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus virginianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'guaranteed',
        funFact: "Shenandoah has one of the highest white-tailed deer densities of any national park — over 6,000 animals. Skyline Drive is famous for deer sightings at dusk, when dozens can be seen grazing park meadows simultaneously." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Shenandoah hosts about 600 black bears — one of the highest densities in the eastern US. Bears are frequently sighted along Skyline Drive, particularly in fall when they gorge on acorns and berries to prepare for winter." },
      { name: 'Wild Turkey', emoji: '🦃', animalType: 'bird',
        scientificName: 'Meleagris gallopavo',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Wild turkeys are year-round residents throughout Shenandoah. In spring, gobbling toms display along Skyline Drive at dawn. Flocks of 20–30 birds, including hens with poults, are frequently seen in late summer." },
      { name: 'Barred Owl', emoji: '🦉', animalType: 'bird',
        scientificName: 'Strix varia',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Barred owls are common in Shenandoah's mature forests. Their call — often described as 'Who cooks for you? Who cooks for you-all?' — frequently rings out at dusk along the AT and on still evenings near campgrounds." },
      { name: 'Eastern Box Turtle', emoji: '🐢', animalType: 'reptile',
        scientificName: 'Terrapene carolina',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Eastern box turtles can live 100+ years in the wild and maintain home ranges of just a few acres their entire lives. They are a Virginia state reptile and frequently encountered crossing Skyline Drive after rains." },
      { name: 'Timber Rattlesnake', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Crotalus horridus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        funFact: "Timber rattlesnakes are present in Shenandoah and occasionally seen sunning on rocky outcrops. They are shy, non-aggressive, and rarely encountered — but worth watching for on rocky ridge trails in summer." },
      { name: 'Spring Peeper', emoji: '🐸', animalType: 'amphibian',
        scientificName: 'Pseudacris crucifer',
        seasons: ['spring'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Spring peepers are small as a thumbnail but produce a deafening chorus in Shenandoah's wetlands from March through April. Thousands calling together from a single pond can be heard half a mile away — the unmistakable sound of spring's arrival." },
      { name: 'Groundhog', emoji: '🦫', animalType: 'mammal',
        scientificName: 'Marmota monax',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Groundhogs (woodchucks) are highly visible at Shenandoah's meadow overlooks along Skyline Drive, sitting upright on rocks and grazing in the open. They are true hibernators, disappearing from October through February." },
    ],
  },

  {
    id: 'newrivergorge',
    name: 'New River Gorge National Park',
    state: 'West Virginia',
    stateCodes: ['WV'],
    lat: 37.8679, lng: -81.0814,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'neri',
    animals: [],
  },

  {
    id: 'cuyahogavalley',
    name: 'Cuyahoga Valley National Park',
    state: 'Ohio',
    stateCodes: ['OH'],
    lat: 41.2808, lng: -81.5678,
    emoji: '🦫',
    locationType: 'nationalPark',
    npsCode: 'cuva',
    animals: [],
  },

  {
    id: 'isleroyale',
    name: 'Isle Royale National Park',
    state: 'Michigan',
    stateCodes: ['MI'],
    lat: 48.0058, lng: -88.8312,
    emoji: '🐺',
    locationType: 'nationalPark',
    npsCode: 'isro',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHEAST NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'greatsmokymountains',
    name: 'Great Smoky Mountains National Park',
    state: 'Tennessee / North Carolina',
    stateCodes: ['TN', 'NC'],
    lat: 35.6117, lng: -83.4895,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'grsm',
    animals: [
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Great Smoky Mountains has one of the densest black bear populations in the eastern US — roughly 1,900 bears, or about 2 per square mile. Cades Cove at dusk is one of the most reliable bear-watching spots in North America." },
      { name: 'White-tailed Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus virginianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'guaranteed',
        funFact: "White-tailed deer were nearly extirpated from the Smokies by 1930 but rebounded dramatically after the park was established. Cades Cove meadows hold the highest concentrations; 50+ deer in a single field is not unusual." },
      { name: 'Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'unlikely',
        funFact: "Elk were reintroduced to the Smokies in 2001 after a 150-year absence. The herd now numbers 200+ animals concentrated in the Cataloochee Valley. Fall bugling in Cataloochee is now one of the most spectacular wildlife events in the eastern US." },
      { name: 'Wild Turkey', emoji: '🦃', animalType: 'bird',
        scientificName: 'Meleagris gallopavo',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Wild turkeys are a common sight in Cades Cove and Cataloochee Valley. Males strut and display in March and April; gobblers can weigh over 20 lbs. Large flocks of hens and young gather in meadows through summer and fall." },
      { name: 'Eastern Hellbender', emoji: '🐸', animalType: 'amphibian',
        scientificName: 'Cryptobranchus alleganiensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'exceptional',
        funFact: "The eastern hellbender is North America's largest salamander, reaching nearly 3 feet. The Smokies hold the last healthy wild populations in the Southeast. These fully aquatic giants absorb oxygen through their wrinkled skin and live under boulders in cold, fast-moving streams." },
      { name: 'Red Salamander', emoji: '🐸', animalType: 'amphibian',
        scientificName: 'Pseudotriton ruber',
        seasons: ['spring', 'fall'], bestSeason: 'spring', rarity: 'rare',
        funFact: "The Great Smoky Mountains host more salamander species than anywhere else in the world — 30 species — earning it the nickname 'Salamander Capital of the World.' The brilliant red-orange red salamander is one of the most striking." },
      { name: 'Eastern Box Turtle', emoji: '🐢', animalType: 'reptile',
        scientificName: 'Terrapene carolina',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Eastern box turtles are common throughout the Smokies' forests. They may live 100+ years and maintain the same small home range their entire lives. After summer rains, they're frequently found on park trails." },
      { name: 'Northern Copperhead', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Agkistrodon contortrix',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Copperheads are the most commonly encountered venomous snake in the Smokies, though bites are rare. Their leaf-litter camouflage is so effective they can be nearly invisible on forest trails — look carefully near rocky outcrops and log piles." },
      { name: 'Synchronous Firefly', emoji: '🪲', animalType: 'insect',
        scientificName: 'Photinus carolinus',
        seasons: ['summer'], bestSeason: 'summer', rarity: 'rare',
        funFact: "The Smokies host one of only a few species of synchronous fireflies in North America. For two weeks in June, thousands of males flash in perfect unison in Elkmont's forest — one of the most magical natural spectacles in the US. A lottery system controls viewing access." },
    ],
  },

  {
    id: 'biscayne',
    name: 'Biscayne National Park',
    state: 'Florida',
    stateCodes: ['FL'],
    lat: 25.4820, lng: -80.4272,
    emoji: '🐠',
    locationType: 'nationalPark',
    npsCode: 'bisc',
    animals: [],
  },

  {
    id: 'drytortugas',
    name: 'Dry Tortugas National Park',
    state: 'Florida',
    stateCodes: ['FL'],
    lat: 24.6282, lng: -82.8733,
    emoji: '🦀',
    locationType: 'nationalPark',
    npsCode: 'drto',
    animals: [],
  },

  {
    id: 'congaree',
    name: 'Congaree National Park',
    state: 'South Carolina',
    stateCodes: ['SC'],
    lat: 33.7978, lng: -80.7783,
    emoji: '🦉',
    locationType: 'nationalPark',
    npsCode: 'cong',
    animals: [],
  },

  {
    id: 'mammothcave',
    name: 'Mammoth Cave National Park',
    state: 'Kentucky',
    stateCodes: ['KY'],
    lat: 37.1862, lng: -86.1003,
    emoji: '🦇',
    locationType: 'nationalPark',
    npsCode: 'maca',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MIDWEST NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'voyageurs',
    name: 'Voyageurs National Park',
    state: 'Minnesota',
    stateCodes: ['MN'],
    lat: 48.4839, lng: -92.8385,
    emoji: '🦦',
    locationType: 'nationalPark',
    npsCode: 'voya',
    animals: [],
  },

  {
    id: 'indianadunes',
    name: 'Indiana Dunes National Park',
    state: 'Indiana',
    stateCodes: ['IN'],
    lat: 41.6533, lng: -87.0524,
    emoji: '🦢',
    locationType: 'nationalPark',
    npsCode: 'indu',
    animals: [],
  },

  {
    id: 'badlands',
    name: 'Badlands National Park',
    state: 'South Dakota',
    stateCodes: ['SD'],
    lat: 43.8554, lng: -102.3397,
    emoji: '🦬',
    locationType: 'nationalPark',
    npsCode: 'badl',
    animals: [
      { name: 'American Bison', emoji: '🦬', animalType: 'mammal',
        scientificName: 'Bison bison',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Bison were reintroduced to the Badlands in 1963; the herd now numbers nearly 1,200. They're most visible from the park road grazing the mixed-grass prairie — particularly in late afternoon light when their massive dark shapes stand out against the eroded formations." },
      { name: 'Pronghorn', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Antilocapra americana',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Pronghorn are extremely common throughout the Badlands' open prairie — easily visible from the park road year-round. They can sustain speeds of 55 mph and maintain 40 mph for miles, making them the second-fastest land animal on Earth." },
      { name: 'Black-tailed Prairie Dog', emoji: '🐿️', animalType: 'mammal',
        scientificName: 'Cynomys ludovicianus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "The Badlands contains one of North America's largest remaining black-tailed prairie dog towns. These highly social rodents live in complex family groups and maintain elaborate burrow systems that support over 160 wildlife species including endangered black-footed ferrets." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Coyotes are highly visible in the Badlands, often seen trotting the prairie in broad daylight hunting prairie dogs and rabbits. Their chorus of yips and howls at dusk is the signature sound of the Great Plains night." },
      { name: 'Prairie Rattlesnake', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Crotalus viridis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Prairie rattlesnakes are the most common venomous snake in the Badlands. They're most active on warm evenings hunting mice and prairie dogs, and often bask on warm rocks near prairie dog towns. Give them wide berth — they rarely strike without warning." },
      { name: 'Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'unlikely',
        funFact: "Bighorn sheep were extirpated from the Badlands but reintroduced in 1964; about 200 remain. Their soft, concave hooves grip the steep eroded formations better than any mountaineering boot, allowing them to scramble seemingly vertical cliff faces with ease." },
      { name: 'Swift Fox', emoji: '🦊', animalType: 'mammal',
        scientificName: 'Vulpes velox',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'rare',
        funFact: "The swift fox — the smallest wild canid in North America — was reintroduced to the Badlands after extirpation. No bigger than a house cat, they're most often seen at dusk near prairie dog colonies, which provide both prey and ready-made dens." },
    ],
  },

  {
    id: 'windcave',
    name: 'Wind Cave National Park',
    state: 'South Dakota',
    stateCodes: ['SD'],
    lat: 43.5570, lng: -103.4785,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'wica',
    animals: [],
  },

  {
    id: 'theodoreroosevelt',
    name: 'Theodore Roosevelt National Park',
    state: 'North Dakota',
    stateCodes: ['ND'],
    lat: 46.9790, lng: -103.5387,
    emoji: '🐎',
    locationType: 'nationalPark',
    npsCode: 'thro',
    animals: [],
  },

  {
    id: 'gatewayarch',
    name: 'Gateway Arch National Park',
    state: 'Missouri',
    stateCodes: ['MO'],
    lat: 38.6247, lng: -90.1848,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'jeff',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // SOUTHWEST NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'grandcanyon',
    name: 'Grand Canyon National Park',
    state: 'Arizona',
    stateCodes: ['AZ'],
    lat: 36.1069, lng: -112.1129,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'grca',
    animals: [
      { name: 'California Condor', emoji: '🦅', animalType: 'bird',
        scientificName: 'Gymnogyps californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'rare',
        funFact: "The California condor is North America's largest flying bird, with a 9.5-foot wingspan. The Grand Canyon is the best place in the world to see one — soaring thermals bring them past the South Rim regularly. Once down to just 27 birds, the population has recovered to 500+ thanks to intensive recovery efforts." },
      { name: 'Desert Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis nelsoni',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Desert bighorn sheep are supremely adapted to the canyon's extreme environment — they can lose 30% of their body weight during drought and recover fully when water is found. Look for them on the steep inner-canyon walls, navigating seemingly vertical drops with ease." },
      { name: 'Mule Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus hemionus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Mule deer are abundant on the Grand Canyon's rims and in the inner canyon. They've become very habituated to visitors on the South Rim — close approaches are common at Mather Point and along the Rim Trail, though feeding them is prohibited." },
      { name: 'Common Raven', emoji: '🐦', animalType: 'bird',
        scientificName: 'Corvus corax',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Ravens are the most conspicuous year-round wildlife at Grand Canyon, boldly raiding unattended lunches at the rim overlooks. They play on thermal updrafts rising from the canyon walls purely for fun — tumbling, rolling, and soaring for hours without a flap." },
      { name: 'Rock Squirrel', emoji: '🐿️', animalType: 'mammal',
        scientificName: 'Otospermophilus variegatus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "Rock squirrels are the large, bushy-tailed squirrels seen at every Grand Canyon overlook. They're bold enough to steal food directly from hands and are responsible for more tourist injuries than rattlesnakes. They bite hard — don't feed them." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'likely',
        funFact: "Coyotes range throughout the Grand Canyon, from the rim forests to the inner canyon. They're most often seen at dawn trotting the rim trails. In the canyon's harsh environment, they've been observed hunting cooperatively with badgers to flush out ground squirrels." },
      { name: 'Grand Canyon Rattlesnake', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Crotalus oreganus abyssus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        funFact: "The Grand Canyon rattlesnake is found nowhere else on Earth — it evolved in isolation within the canyon. Its pinkish coloration matches the Redwall Limestone of the inner canyon. A sighting on the Bright Angel or North Kaibab Trail is a genuine rarity." },
      { name: 'Peregrine Falcon', emoji: '🦅', animalType: 'bird',
        scientificName: 'Falco peregrinus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Peregrine falcons nest on the Grand Canyon's cliff faces and are regularly seen stooping at speeds exceeding 200 mph on unsuspecting ravens and swifts. The canyon's vertical walls provide ideal nest ledges safe from mammalian predators." },
      { name: 'Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis',
        seasons: ['fall', 'winter', 'spring'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Elk are commonly seen on the North Rim and the forested South Rim of the Grand Canyon. They were reintroduced to the South Rim in the 1910s and the population now numbers in the hundreds. Fall rut brings bulls to meadows near the rim at dusk, bugling across the canyon." },
    ],
  },

  {
    id: 'zion',
    name: 'Zion National Park',
    state: 'Utah',
    stateCodes: ['UT'],
    lat: 37.2982, lng: -113.0263,
    emoji: '🦁',
    locationType: 'nationalPark',
    npsCode: 'zion',
    animals: [
      { name: 'California Condor', emoji: '🦅', animalType: 'bird',
        scientificName: 'Gymnogyps californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'rare',
        funFact: "California condors, freed from the Vermilion Cliffs release site just 60 miles away, now regularly soar over Zion Canyon. The Angels Landing trail is one of the best places to scan for them riding thermals above the sandstone walls." },
      { name: 'Desert Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis nelsoni',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "About 550 desert bighorn sheep inhabit Zion. They're most visible in early morning on the steep red walls of Zion Canyon, where their sandy-brown coats blend with the Navajo Sandstone. Lambs are often seen in spring near the canyon floor." },
      { name: 'Mule Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus hemionus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Mule deer are common throughout Zion Canyon and very habituated to visitors along the Pa'rus Trail and near the visitor center. Bucks with velvet antlers are a regular sight in summer; the rut brings larger bucks out in November." },
      { name: 'Ringtail', emoji: '🦝', animalType: 'mammal',
        scientificName: 'Bassariscus astutus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        funFact: "Ringtails are Arizona's state mammal and a secretive resident of Zion's rocky canyon walls. Almost entirely nocturnal, they're among the most agile mammals in North America — able to rotate their hind feet 180° to descend sheer rock faces headfirst." },
      { name: 'Canyon Tree Frog', emoji: '🐸', animalType: 'amphibian',
        scientificName: 'Dryophytes arenicolor',
        seasons: ['spring', 'summer'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Canyon tree frogs cling to the wet sandstone walls along Zion's streams, their cryptic coloration blending perfectly with the rock. After spring rains their explosive chorus fills the canyon — a surprisingly loud rattling trill from a frog that fits in a teaspoon." },
      { name: 'Great Basin Rattlesnake', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Crotalus oreganus lutosus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        funFact: "Great Basin rattlesnakes are present in Zion's lower-elevation habitats but rarely seen. They're most active at dusk in warm weather. If encountered, give them space — they provide critical rodent control in the park's ecosystem." },
      { name: 'Peregrine Falcon', emoji: '🦅', animalType: 'bird',
        scientificName: 'Falco peregrinus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Peregrine falcons nest in Zion's vertical cliffs. The narrow canyon concentrates their hunting — watch for them stooping at White-throated Swifts that winter and nest on the canyon walls in huge, chattering flocks." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Coyotes are common in Zion and often seen along the Virgin River corridor at dawn. They've learned to surf the wake of river-tubing visitors — literally wading in after people pass to catch disoriented crayfish stirred up from the riverbed." },
    ],
  },

  {
    id: 'brycecanyon',
    name: 'Bryce Canyon National Park',
    state: 'Utah',
    stateCodes: ['UT'],
    lat: 37.5930, lng: -112.1871,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'brca',
    animals: [],
  },

  {
    id: 'arches',
    name: 'Arches National Park',
    state: 'Utah',
    stateCodes: ['UT'],
    lat: 38.7331, lng: -109.5925,
    emoji: '🦎',
    locationType: 'nationalPark',
    npsCode: 'arch',
    animals: [],
  },

  {
    id: 'canyonlands',
    name: 'Canyonlands National Park',
    state: 'Utah',
    stateCodes: ['UT'],
    lat: 38.2000, lng: -109.9300,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'cany',
    animals: [],
  },

  {
    id: 'capitolreef',
    name: 'Capitol Reef National Park',
    state: 'Utah',
    stateCodes: ['UT'],
    lat: 38.0877, lng: -111.1429,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'care',
    animals: [],
  },

  {
    id: 'mesaverde',
    name: 'Mesa Verde National Park',
    state: 'Colorado',
    stateCodes: ['CO'],
    lat: 37.2309, lng: -108.4618,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'meve',
    animals: [],
  },

  {
    id: 'petrifiedforest',
    name: 'Petrified Forest National Park',
    state: 'Arizona',
    stateCodes: ['AZ'],
    lat: 35.0654, lng: -109.7870,
    emoji: '🦎',
    locationType: 'nationalPark',
    npsCode: 'pefo',
    animals: [],
  },

  {
    id: 'saguaro',
    name: 'Saguaro National Park',
    state: 'Arizona',
    stateCodes: ['AZ'],
    lat: 32.2967, lng: -110.9919,
    emoji: '🦜',
    locationType: 'nationalPark',
    npsCode: 'sagu',
    animals: [
      { name: "Gambel's Quail", emoji: '🐦', animalType: 'bird',
        scientificName: 'Callipepla gambelii',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'guaranteed',
        funFact: "Gambel's quail are Saguaro's most visible bird — coveys of 10–20 scurry between cacti at dawn and dusk, the males' distinctive topknot bobbing as they run. In spring, family groups with tiny chicks parade single-file through the cactus forest." },
      { name: 'Gila Woodpecker', emoji: '🐦', animalType: 'bird',
        scientificName: 'Melanerpes uropygialis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "The Gila woodpecker is the architect of the Sonoran Desert — it excavates nest holes in saguaro cacti, which then dry into hard 'saguaro boots.' These cavities are later used by elf owls, kestrels, and flycatchers, making the Gila woodpecker a keystone species." },
      { name: 'Cactus Wren', emoji: '🐦', animalType: 'bird',
        scientificName: 'Campylorhynchus brunneicapillus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Arizona's state bird builds its football-shaped nest deep in cholla cactus — the spines deter predators. Cactus wrens are year-round residents that don't need to drink water, getting all their moisture from insects and cactus fruit." },
      { name: 'Greater Roadrunner', emoji: '🐦', animalType: 'bird',
        scientificName: 'Geococcyx californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "The roadrunner is Saguaro's most charismatic bird — a ground-dwelling cuckoo that can sprint at 20 mph to catch lizards, snakes, and even rattlesnakes. It warms up on cold desert mornings by spreading its back feathers to expose dark skin to the sun." },
      { name: 'Javelina', emoji: '🐗', animalType: 'mammal',
        scientificName: 'Pecari tajacu',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Collared peccaries (javelinas) are a uniquely American desert mammal — not pigs but a separate family. Herds of 6–12 move through the cactus forest in early morning, using their tough snouts to eat prickly pear pads, spines and all. Their musk glands on their rumps give them a strong, distinctive odor." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Saguaro's coyotes are highly adaptable omnivores that have thrived alongside Tucson's urban sprawl. They hunt rabbits and rodents at dawn and dusk, and play an important ecological role dispersing saguaro seeds in their scat across the desert." },
      { name: 'Gila Monster', emoji: '🦎', animalType: 'reptile',
        scientificName: 'Heloderma suspectum',
        seasons: ['spring', 'summer'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "The Gila monster is one of only two venomous lizards in the world and one of Saguaro's most sought-after sightings. Despite its fearsome reputation it's slow-moving and docile; it spends 95% of its life underground, emerging only after rains to hunt birds' eggs and small mammals." },
    ],
  },

  {
    id: 'whitesands',
    name: 'White Sands National Park',
    state: 'New Mexico',
    stateCodes: ['NM'],
    lat: 32.7872, lng: -106.3259,
    emoji: '🦎',
    locationType: 'nationalPark',
    npsCode: 'whsa',
    animals: [],
  },

  {
    id: 'guadalupemountains',
    name: 'Guadalupe Mountains National Park',
    state: 'Texas',
    stateCodes: ['TX'],
    lat: 31.9231, lng: -104.8714,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'gumo',
    animals: [],
  },

  {
    id: 'bigbend',
    name: 'Big Bend National Park',
    state: 'Texas',
    stateCodes: ['TX'],
    lat: 29.1275, lng: -103.2425,
    emoji: '🐆',
    locationType: 'nationalPark',
    npsCode: 'bibe',
    animals: [
      { name: 'Javelina', emoji: '🐗', animalType: 'mammal',
        scientificName: 'Pecari tajacu',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Collared peccaries (javelinas) are among the most commonly seen mammals at Big Bend, often encountered in groups of 10–20 near the Chisos Basin and Castolon. Despite resembling pigs, they're in an entirely separate family. They communicate by rubbing scent glands on rocks and each other." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Black bears colonized Big Bend's Chisos Mountains naturally from Mexico in the 1990s. The Chisos are an isolated 'sky island' rising from the Chihuahuan Desert — ideal bear habitat. They're regularly seen near the Chisos Basin campground and lodge." },
      { name: 'Greater Roadrunner', emoji: '🐦', animalType: 'bird',
        scientificName: 'Geococcyx californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Greater roadrunners are iconic at Big Bend, seen year-round trotting along park roads and desert trails. They can run 15 mph and regularly eat rattlesnakes, pinning them with their bill and slamming them against rocks. Texas's state bird." },
      { name: 'Western Diamondback Rattlesnake', emoji: '🐍', animalType: 'reptile',
        scientificName: 'Crotalus atrox',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "The western diamondback is Big Bend's most common venomous snake and one of the most encountered reptiles in the park. They're most active at dusk on warm evenings, often found on roads or desert trails. They rattle as a warning — respect the signal and give them space." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Coyotes are highly visible at Big Bend, often seen hunting lizards and mice in the desert scrub near the park road. They've become bold in the Chisos Basin and around campgrounds — all food must be stored properly." },
      { name: 'Peregrine Falcon', emoji: '🦅', animalType: 'bird',
        scientificName: 'Falco peregrinus',
        seasons: ['spring', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Big Bend's tall volcanic cliffs provide nesting habitat for peregrine falcons. The park is a key migration corridor — hundreds of peregrines and other raptors move through in spring and fall along the Rio Grande corridor, which funnels birds heading toward Mexico." },
      { name: 'Mule Deer', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Odocoileus hemionus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Mule deer are abundant in the Chisos Mountains and desert grasslands of Big Bend. They're highly adapted to arid conditions, able to go days without water by metabolizing moisture from their food. Large groups are often seen near the Chisos Basin campground at dawn." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ROCKY MOUNTAIN NATIONAL PARKS & MONUMENTS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'grandteton',
    name: 'Grand Teton National Park',
    state: 'Wyoming',
    stateCodes: ['WY'],
    lat: 43.7904, lng: -110.6818,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'grte',
    animals: [
      { name: 'American Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'very_likely',
        funFact: "Grand Teton hosts one of the largest elk herds in the Greater Yellowstone Ecosystem — thousands migrate through the park each fall. The bugling rut in September fills the Snake River valley; Oxbow Bend at dawn is legendary for elk sightings." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Grand Teton is one of the premier moose-viewing locations in the lower 48. Willow flats near Jackson Lake Lodge and the Oxbow Bend area reliably produce moose sightings. Cows with newborn calves in June are among the most thrilling wildlife sightings in the park." },
      { name: 'Grizzly Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos horribilis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Grizzly bears regularly visit Grand Teton as part of the Greater Yellowstone population. Spring is prime viewing — bears emerge lean from their dens and hunt elk calves in open sagebrush flats near Willow Flats and Antelope Flats." },
      { name: 'Pronghorn', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Antilocapra americana',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Grand Teton's pronghorn herd undertakes one of North America's longest migrations — 150 miles to Wyoming's Upper Green River Basin each winter. The return in spring through the park's sagebrush flats is a dramatic seasonal event." },
      { name: 'American Beaver', emoji: '🦫', animalType: 'mammal',
        scientificName: 'Castor canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "American beavers are commonly seen in Grand Teton's wetlands and slow-moving channels. Their dams create critical habitat for moose, waterfowl, and fish. The Oxbow Bend area is particularly productive for beaver sightings at dusk." },
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Bald eagles nest in Grand Teton's large cottonwood trees along the Snake River and are regularly seen soaring over Jackson Lake and the river channels. Up to 60 individuals winter in the park, concentrated at open water." },
      { name: 'Sandhill Crane', emoji: '🐦', animalType: 'bird',
        scientificName: 'Antigone canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Greater sandhill cranes nest in Grand Teton's wet meadows and are a regular sight in Willow Flats and near Oxbow Bend. Their prehistoric bugling calls carry for miles. Young cranes ('colts') follow their parents all summer, learning the migration routes." },
    ],
  },

  {
    id: 'rockymountain',
    name: 'Rocky Mountain National Park',
    state: 'Colorado',
    stateCodes: ['CO'],
    lat: 40.3428, lng: -105.6836,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'romo',
    animals: [
      { name: 'American Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'very_likely',
        funFact: "Rocky Mountain NP has one of the largest elk herds in North America — about 3,000 animals. The fall rut in Moraine Park and Horseshoe Park is spectacular: dozens of bugling bulls visible simultaneously in the meadows at dawn." },
      { name: 'Rocky Mountain Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Rocky Mountain National Park is the most reliable place in Colorado to see bighorn sheep. Dozens gather on the steep slopes above Trail Ridge Road in summer. Their explosive headbutting clashes in November — rams hitting at 20 mph — produce a crack audible hundreds of yards away." },
      { name: 'American Pika', emoji: '🐿️', animalType: 'mammal',
        scientificName: 'Ochotona princeps',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "American pikas are golf-ball-sized relatives of rabbits that live in alpine talus fields along Trail Ridge Road. They don't hibernate — instead they 'hay' all summer, cutting and curing plants to store under rocks for winter. They're a climate change canary: heat kills them within hours." },
      { name: 'Yellow-bellied Marmot', emoji: '🦫', animalType: 'mammal',
        scientificName: 'Marmota flaviventris',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Yellow-bellied marmots are Rocky Mountain's most visible alpine mammal, basking on boulders along Trail Ridge Road and whistling sharp alarm calls when threatened. They hibernate from September through April, emerging to find flowers already blooming in the snowmelt." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'unlikely',
        funFact: "Moose were rare in Rocky Mountain NP until the 1970s when they expanded south from Wyoming. A small but growing population now inhabits the willowy riparian corridors on the park's west side, near Grand Lake and Kawuneeche Valley." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'unlikely',
        funFact: "Black bears inhabit Rocky Mountain NP's forested zones below treeline. They're most active in fall during hyperphagia, gorging on berries and acorns to prepare for denning. Encounters are more common than in many parks — all food must be stored in bear boxes." },
      { name: 'Steller\'s Jay', emoji: '🐦', animalType: 'bird',
        scientificName: 'Cyanocitta stelleri',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Steller's jays are Rocky Mountain's most conspicuous birds — bold, noisy, and spectacularly crested in deep blue and black. They're highly intelligent, capable of mimicking the calls of red-tailed hawks to frighten other birds from food sources." },
    ],
  },

  {
    id: 'glacier',
    name: 'Glacier National Park',
    state: 'Montana',
    stateCodes: ['MT'],
    lat: 48.7596, lng: -113.7870,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'glac',
    wideNet: true,
    animals: [
      { name: 'Grizzly Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos horribilis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "Glacier National Park is one of the last strongholds of the grizzly bear in the lower 48 — about 300 grizzlies live here. The Going-to-the-Sun Road corridor in spring, when bears forage on glacier lily bulbs in open avalanche chutes, offers some of the most reliable grizzly viewing anywhere." },
      { name: 'Mountain Goat', emoji: '🐐', animalType: 'mammal',
        scientificName: 'Oreamnos americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Mountain goats are Glacier's signature alpine mammal. They inhabit the high cliffs and snowfields that most other animals avoid, their cloven hooves equipped with rubbery pads for traction on bare rock. Families are often spotted from the Going-to-the-Sun Road near Logan Pass." },
      { name: 'Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Rocky Mountain bighorn sheep graze Glacier's high meadows and cliffs alongside mountain goats. The two species rarely interact despite sharing terrain. Bighorn rams congregate in bachelor groups through summer, preparing for the November rut." },
      { name: 'Wolverine', emoji: '🦡', animalType: 'mammal',
        scientificName: 'Gulo gulo',
        seasons: ['winter', 'spring'], bestSeason: 'winter', rarity: 'exceptional',
        funFact: "Wolverines are the park's most elusive large predator — solitary and wide-ranging, covering up to 15 miles a day. Glacier is one of the last places in the lower 48 with a viable wolverine population. They depend on late-lying snow for denning; climate change threatens their future here." },
      { name: 'Gray Wolf', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis lupus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'rare',
        funFact: "Gray wolves returned to Glacier on their own from Canada in the 1980s, a decade before the Yellowstone reintroduction. Several packs now roam the park; the North Fork Valley is the best area to find wolf signs, including tracks in winter snow." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'unlikely',
        funFact: "Moose are common in Glacier's riparian corridors, particularly on the park's west side along McDonald Creek and the North Fork of the Flathead River. Bulls with massive antlers are a thrilling sight in September during the rut." },
      { name: 'American Pika', emoji: '🐿️', animalType: 'mammal',
        scientificName: 'Ochotona princeps',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "American pikas are common in Glacier's alpine talus fields, easily found near Logan Pass and along the Hidden Lake trail. Their high-pitched 'eek' call betrays their presence among the rocks. They're highly sensitive to heat — a canary species for mountain ecosystem health." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Black bears are common throughout Glacier's lower-elevation forests and berry patches. The park's huckleberry crops in late summer draw bears to open hillsides in large numbers — bear spray is essential on all trails from August through October." },
    ],
  },

  {
    id: 'greatsanddunes',
    name: 'Great Sand Dunes National Park',
    state: 'Colorado',
    stateCodes: ['CO'],
    lat: 37.7928, lng: -105.5943,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'grsa',
    animals: [],
  },

  {
    id: 'blackcanyon',
    name: 'Black Canyon of the Gunnison National Park',
    state: 'Colorado',
    stateCodes: ['CO'],
    lat: 38.5754, lng: -107.7416,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'blca',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEST COAST NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'olympic',
    name: 'Olympic National Park',
    state: 'Washington',
    stateCodes: ['WA'],
    lat: 47.8021, lng: -123.6044,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'olym',
    wideNet: true,
    animals: [
      { name: 'Roosevelt Elk', emoji: '🦌', animalType: 'mammal',
        scientificName: 'Cervus canadensis roosevelti',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Roosevelt elk — the largest elk subspecies — were the original reason the park was protected. About 5,000 live in Olympic; the Hoh Rain Forest and Quinault Rain Forest valleys are prime habitat. The bugling rut in September and October is extraordinary." },
      { name: 'Black Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus americanus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Olympic's black bears are among the most food-secure in the Northwest, thriving on berries, salmon carcasses, and insects in the diverse habitats. They're frequently seen on the Hurricane Ridge prairies in summer, rolling in lupine meadows in the long alpine evenings." },
      { name: 'Olympic Marmot', emoji: '🦫', animalType: 'mammal',
        scientificName: 'Marmota olympus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "The Olympic marmot is found only within Olympic National Park — nowhere else on Earth. These large, social rodents colonize high-elevation meadows and whistle sharp alarm calls at passing eagles and hikers. Their population has declined significantly in recent decades." },
      { name: 'Harbor Seal', emoji: '🦭', animalType: 'marine',
        scientificName: 'Phoca vitulina',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Harbor seals haul out on the Olympic Peninsula's coastal beaches and offshore rocks year-round. Dozens may be seen resting together at Kalaloch and Ruby Beach. Mothers with pups are frequently found near the waterline in spring — give them wide berth." },
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'likely',
        funFact: "Bald eagles are year-round residents of Olympic's coast and rivers. The park's rivers fill with spawning salmon each fall, drawing large numbers of eagles that can be watched fishing from the banks with remarkable up-close views." },
      { name: 'Pacific Giant Salamander', emoji: '🐸', animalType: 'amphibian',
        scientificName: 'Dicamptodon tenebrosus',
        seasons: ['spring', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "The Pacific giant salamander is the world's largest terrestrial salamander, sometimes exceeding 12 inches. They're found in Olympic's cool, clear streams — sometimes living entirely aquatically as 'neotenic' adults that never metamorphose. They can bark." },
      { name: 'River Otter', emoji: '🦦', animalType: 'mammal',
        scientificName: 'Lontra canadensis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'winter', rarity: 'unlikely',
        funFact: "North American river otters are active year-round in Olympic's coastal lagoons, estuaries, and lower rivers. The Sol Duc and Hoh river systems are particularly good — look for their spraint (droppings) on prominent rocks in the river, a reliable sign of resident territory." },
    ],
  },

  {
    id: 'northcascades',
    name: 'North Cascades National Park',
    state: 'Washington',
    stateCodes: ['WA'],
    lat: 48.7718, lng: -121.2985,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'noca',
    wideNet: true,
    animals: [],
  },

  {
    id: 'mountrainier',
    name: 'Mount Rainier National Park',
    state: 'Washington',
    stateCodes: ['WA'],
    lat: 46.8523, lng: -121.7603,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'mora',
    animals: [],
  },

  {
    id: 'craterlake',
    name: 'Crater Lake National Park',
    state: 'Oregon',
    stateCodes: ['OR'],
    lat: 42.9446, lng: -122.1090,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'crla',
    animals: [],
  },

  {
    id: 'redwood',
    name: 'Redwood National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 41.2132, lng: -124.0046,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'redw',
    animals: [],
  },

  {
    id: 'lassenvolcanic',
    name: 'Lassen Volcanic National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 40.4977, lng: -121.4207,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'lavo',
    animals: [],
  },

  {
    id: 'yosemite',
    name: 'Yosemite National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 37.8651, lng: -119.5383,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'yose',
    animals: [],
  },

  {
    id: 'kingscanyon',
    name: 'Kings Canyon National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 36.8879, lng: -118.5551,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'kica',
    animals: [],
  },

  {
    id: 'sequoia',
    name: 'Sequoia National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 36.4864, lng: -118.5658,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'sequ',
    animals: [],
  },

  {
    id: 'joshuatree',
    name: 'Joshua Tree National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 33.8734, lng: -115.9010,
    emoji: '🦎',
    locationType: 'nationalPark',
    npsCode: 'jotr',
    animals: [
      { name: "Gambel's Quail", emoji: '🐦', animalType: 'bird',
        scientificName: 'Callipepla gambelii',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'guaranteed',
        funFact: "Gambel's quail are Joshua Tree's most reliably seen bird — large coveys gather at water sources at dawn, the males' topknots catching the desert light. In spring they lead strings of tiny chicks through the Joshua tree forest, one of the desert's most endearing wildlife spectacles." },
      { name: 'Greater Roadrunner', emoji: '🐦', animalType: 'bird',
        scientificName: 'Geococcyx californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Joshua Tree's roadrunners patrol the boulder fields and sandy washes for lizards, snakes, and insects. They can take down a rattlesnake by grabbing it behind the head and bashing it against a rock — a behavior that never fails to impress." },
      { name: 'Coyote', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis latrans',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Coyotes are Joshua Tree's top predator, active at dawn and dusk in the open desert flats. Their haunting calls echo across the park on still nights. They're important seed dispersers for native plants including Joshua trees themselves." },
      { name: 'Desert Bighorn Sheep', emoji: '🐑', animalType: 'mammal',
        scientificName: 'Ovis canadensis nelsoni',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "About 250 desert bighorn sheep inhabit Joshua Tree's rocky ranges, having evolved to survive on minimal water by metabolizing moisture from desert plants. The Wonderland of Rocks, Sheep Pass, and Pinto Basin areas offer the best chance of spotting these cliff-dwelling masters." },
      { name: 'Desert Tortoise', emoji: '🐢', animalType: 'reptile',
        scientificName: 'Gopherus agassizii',
        seasons: ['spring', 'fall'], bestSeason: 'spring', rarity: 'unlikely',
        funFact: "The Mojave desert tortoise is a living relic — these tortoises can live 80+ years and spend up to 95% of their lives in underground burrows. They emerge in spring to feed on wildflowers and grasses, storing water in their bladder to survive the brutal summer heat." },
      { name: 'Black-tailed Jackrabbit', emoji: '🐰', animalType: 'mammal',
        scientificName: 'Lepus californicus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "The black-tailed jackrabbit uses its enormous ears as a radiator — the large blood vessels on the ear surface release body heat in hot weather. They're incredibly fast, reaching 40 mph in bounding leaps of up to 20 feet, and are a critical prey species for coyotes, eagles, and bobcats." },
      { name: 'Chuckwalla', emoji: '🦎', animalType: 'reptile',
        scientificName: 'Sauromalus ater',
        seasons: ['spring', 'summer'], bestSeason: 'spring', rarity: 'likely',
        funFact: "The chuckwalla is Joshua Tree's largest lizard — a chunky, plant-eating iguana relative that basks on sun-warmed boulders. When threatened, it wedges itself into a rock crack and inflates its body with air, making it nearly impossible to extract." },
    ],
  },

  {
    id: 'deathvalley',
    name: 'Death Valley National Park',
    state: 'California/Nevada',
    stateCodes: ['CA', 'NV'],
    lat: 36.5054, lng: -117.0794,
    emoji: '🦂',
    locationType: 'nationalPark',
    npsCode: 'deva',
    animals: [],
  },

  {
    id: 'channelislands',
    name: 'Channel Islands National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 34.0069, lng: -119.7785,
    emoji: '🦭',
    locationType: 'nationalPark',
    npsCode: 'chis',
    animals: [
      { name: 'California Sea Otter', emoji: '🦦', animalType: 'marine',
        scientificName: 'Enhydra lutris nereis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'likely',
        funFact: "Sea otters were hunted nearly to extinction off California but are now recovering. They're regularly seen in kelp forests around Santa Cruz Island, floating on their backs and cracking sea urchins on their chests — their voracious appetite for urchins protects the entire kelp forest ecosystem." },
      { name: 'Island Fox', emoji: '🦊', animalType: 'mammal',
        scientificName: 'Urocyon littoralis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "The island fox is found only on six of California's Channel Islands — nowhere else on Earth. Each island population evolved independently into its own subspecies. After crashing to near extinction in the 1990s due to golden eagle predation, all six subspecies have rebounded through an intensive captive-breeding program." },
      { name: 'California Sea Lion', emoji: '🦭', animalType: 'marine',
        scientificName: 'Zalophus californianus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "Channel Islands hosts the largest California sea lion rookery in the world — over 40,000 animals breed on San Miguel Island alone. The males' booming bark and acrobatic underwater hunting make them the most conspicuous wildlife at any Channel Islands landing site." },
      { name: 'Blue Whale', emoji: '🐋', animalType: 'marine',
        scientificName: 'Balaenoptera musculus',
        seasons: ['summer', 'fall'], bestSeason: 'summer', rarity: 'rare',
        funFact: "The Santa Barbara Channel between the mainland and Channel Islands is one of the best places on Earth to see blue whales — the largest animals ever to have lived. Every summer, dozens feed on the dense krill upwellings here. A blue whale's heart is the size of a small car." },
      { name: 'Brown Pelican', emoji: '🐦', animalType: 'bird',
        scientificName: 'Pelecanus occidentalis',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Anacapa Island is the largest California brown pelican breeding colony on the US West Coast. Once nearly extirpated by DDT, the colony now numbers in the tens of thousands. Watching hundreds of pelicans plunge-diving simultaneously into a bait ball is a Channel Islands highlight." },
    ],
  },

  {
    id: 'pinnacles',
    name: 'Pinnacles National Park',
    state: 'California',
    stateCodes: ['CA'],
    lat: 36.4906, lng: -121.1825,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'pinn',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ALASKA NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'kenaifjords',
    name: 'Kenai Fjords National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 59.9195, lng: -150.1585,
    emoji: '🦭',
    locationType: 'nationalPark',
    npsCode: 'kefj',
    wideNet: true,
    animals: [
      { name: 'Humpback Whale', emoji: '🐋', animalType: 'marine',
        scientificName: 'Megaptera novaeangliae',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Kenai Fjords' cold, krill-rich waters are one of Alaska's premier whale watching areas. Humpbacks feed heavily here through summer, often seen bubble-net feeding in synchronized groups — a remarkable cooperative behavior where whales herd fish into a rising column of bubbles." },
      { name: 'Orca', emoji: '🐋', animalType: 'marine',
        scientificName: 'Orcinus orca',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Both resident (fish-eating) and transient (marine mammal-eating) orca populations move through Kenai Fjords. Transient orcas patrol the coastline hunting harbor seals and sea lions with stunning sophistication — a sighting of a hunt near a haul-out is one of Alaska's most intense wildlife experiences." },
      { name: 'Steller Sea Lion', emoji: '🦭', animalType: 'marine',
        scientificName: 'Eumetopias jubatus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Steller sea lions — the world's largest sea lions — haul out on Kenai Fjords' rocky shores in large, boisterous groups. Males can exceed 2,400 lbs. Their roaring colonies at places like Chiswell Islands carry for miles across the water." },
      { name: 'Harbor Seal', emoji: '🦭', animalType: 'marine',
        scientificName: 'Phoca vitulina',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Harbor seals pup on Kenai Fjords' glacier ice floes — a behavior unique to this region. Pupping on ice protects newborns from land predators. As glaciers retreat, this essential habitat is shrinking, making Kenai Fjords a critical conservation frontline." },
      { name: 'Tufted Puffin', emoji: '🐦', animalType: 'bird',
        scientificName: 'Fratercula cirrhata',
        seasons: ['spring', 'summer'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Tufted puffins nest in huge colonies on Kenai Fjords' seabird islands — the Chiswell Islands host tens of thousands. They're expert divers, using their wings to 'fly' underwater to depths of 200 feet. Their comical golden tufts and bright orange bills make them unmistakable." },
    ],
  },

  {
    id: 'glacierbay',
    name: 'Glacier Bay National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 58.6657, lng: -136.9000,
    emoji: '🐋',
    locationType: 'nationalPark',
    npsCode: 'glba',
    wideNet: true,
    animals: [
      { name: 'Humpback Whale', emoji: '🐋', animalType: 'marine',
        scientificName: 'Megaptera novaeangliae',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Glacier Bay is one of the world's most important humpback whale feeding areas. Up to 40+ whales can be present at once in midsummer. Since the moratorium on commercial whaling, humpbacks have returned to numbers not seen in Glacier Bay since the early 20th century." },
      { name: 'Orca', emoji: '🐋', animalType: 'marine',
        scientificName: 'Orcinus orca',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Orcas patrol Glacier Bay's waters in both resident (fish-eating) and transient (mammal-eating) forms. They're frequently seen near harbor seal haul-outs, particularly in Muir Inlet. An orca hunt on unsuspecting harbor seals near a tidewater glacier is unforgettable." },
      { name: 'Harbor Seal', emoji: '🦭', animalType: 'marine',
        scientificName: 'Phoca vitulina',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'spring', rarity: 'very_likely',
        funFact: "Glacier Bay's tidewater glaciers are critical harbor seal pupping habitat. Hundreds of seals haul out on icebergs calved from Johns Hopkins Glacier — the most important glacial harbor seal colony in Alaska. Boat access is restricted near the glacier during pupping season." },
      { name: 'Brown Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Brown bears are commonly seen along Glacier Bay's shorelines, particularly in summer when they dig for clams and catch salmon in river estuaries. Beach-foraging bears at low tide in front of a tidewater glacier wall is one of the most stunning wildlife sights in Alaska." },
      { name: 'Steller Sea Lion', emoji: '🦭', animalType: 'marine',
        scientificName: 'Eumetopias jubatus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "Steller sea lions haul out on rocky points throughout Glacier Bay, their roaring audible long before they're visible. Massive bulls jealously guard territories among dozens of females. Their raucous colonies are one of the bay's most memorable experiences." },
      { name: 'Tufted Puffin', emoji: '🐦', animalType: 'bird',
        scientificName: 'Fratercula cirrhata',
        seasons: ['spring', 'summer'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Tufted puffins nest on Glacier Bay's outer coast islands and are regularly seen during boat tours flying with fish packed crosswise in their brightly-colored bills — sometimes a dozen at a time. Their bright summer plumage with golden facial tufts makes identification easy." },
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Bald eagles are common throughout Glacier Bay, perching on spruce trees along the shoreline and soaring over the bay. They benefit enormously from the abundant marine resources — fish scraps, seal pups, and salmon in season. Nesting pairs return to the same territories year after year." },
    ],
  },

  {
    id: 'katmai',
    name: 'Katmai National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 58.5001, lng: -154.9763,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'katm',
    wideNet: true,
    animals: [
      { name: 'Brown Bear', emoji: '🐻', animalType: 'mammal',
        scientificName: 'Ursus arctos',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "Katmai is the premier bear-watching destination on Earth. About 2,200 brown bears live here — one of the highest densities anywhere. At Brooks Falls in July, dozens of bears stand shoulder-to-shoulder catching sockeye salmon leaping the waterfall, visible from a platform just 50 feet away." },
      { name: 'Sockeye Salmon', emoji: '🐟', animalType: 'marine',
        scientificName: 'Oncorhynchus nerka',
        seasons: ['summer', 'fall'], bestSeason: 'summer', rarity: 'very_likely',
        funFact: "Millions of sockeye salmon return to Katmai's Brooks River each year, turning the water red with spawning fish and drawing the park's famous concentration of bears. Salmon fresh from the sea are bright silver; by spawning time they've turned brilliant crimson with hooked, green-jawed heads." },
      { name: 'Moose', emoji: '🫎', animalType: 'mammal',
        scientificName: 'Alces alces',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'fall', rarity: 'likely',
        funFact: "Alaska moose — the largest subspecies — are commonly seen in Katmai's riparian areas and wetlands. Bulls reach 1,600 lbs and carry the largest antlers of any animal on earth. Cow-calf pairs are frequently encountered wading in lakes and ponds feeding on aquatic vegetation." },
      { name: 'Bald Eagle', emoji: '🦅', animalType: 'bird',
        scientificName: 'Haliaeetus leucocephalus',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'likely',
        funFact: "Bald eagles congregate at Katmai's salmon streams during the runs, stealing fish from bears and each other with aerial precision. Dozens may be perched in trees overlooking Brooks River during peak salmon season, the largest concentration most visitors will ever see." },
      { name: 'Gray Wolf', emoji: '🐺', animalType: 'mammal',
        scientificName: 'Canis lupus',
        seasons: ['spring', 'summer', 'fall', 'winter'], bestSeason: 'summer', rarity: 'rare',
        funFact: "Gray wolves range throughout Katmai, occasionally visible on the park's beaches and open tundra. They're rarely seen near Brooks Camp due to bear competition, but their tracks in river mud are commonly found. Packs here have learned to hunt salmon — an unusual behavior for wolves." },
      { name: 'River Otter', emoji: '🦦', animalType: 'mammal',
        scientificName: 'Lontra canadensis',
        seasons: ['spring', 'summer', 'fall'], bestSeason: 'summer', rarity: 'unlikely',
        funFact: "River otters thrive in Katmai's salmon-rich rivers and lakes, often seen playing and fishing near Brooks Falls alongside the famous bears. They're remarkably agile and will boldly pirate salmon scraps left by feeding bears, seemingly oblivious to the presence of 1,000-lb predators." },
    ],
  },

  {
    id: 'wrangellstelias',
    name: 'Wrangell-St. Elias National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 61.7105, lng: -142.9856,
    emoji: '🦅',
    locationType: 'nationalPark',
    npsCode: 'wrst',
    animals: [],
  },

  {
    id: 'lakeclark',
    name: 'Lake Clark National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 60.4126, lng: -153.4891,
    emoji: '🐻',
    locationType: 'nationalPark',
    npsCode: 'lacl',
    animals: [],
  },

  {
    id: 'gatesofthearctic',
    name: 'Gates of the Arctic National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 67.7776, lng: -153.3088,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'gaar',
    wideNet: true,
    animals: [],
  },

  {
    id: 'kobukvalley',
    name: 'Kobuk Valley National Park',
    state: 'Alaska',
    stateCodes: ['AK'],
    lat: 67.3564, lng: -159.1229,
    emoji: '🦌',
    locationType: 'nationalPark',
    npsCode: 'kova',
    wideNet: true,
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // HAWAII NATIONAL PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'hawaiivolcanoes',
    name: 'Hawaii Volcanoes National Park',
    state: 'Hawaii',
    stateCodes: ['HI'],
    lat: 19.4194, lng: -155.2885,
    emoji: '🌋',
    locationType: 'nationalPark',
    npsCode: 'havo',
    animals: [],
  },

  {
    id: 'haleakala',
    name: 'Haleakalā National Park',
    state: 'Hawaii',
    stateCodes: ['HI'],
    lat: 20.7204, lng: -156.1552,
    emoji: '🦢',
    locationType: 'nationalPark',
    npsCode: 'hale',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PACIFIC ISLANDS & TERRITORIES
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'americansamoa',
    name: 'National Park of American Samoa',
    state: 'American Samoa',
    stateCodes: ['AS'],
    lat: -14.2555, lng: -170.6850,
    emoji: '🦜',
    locationType: 'nationalPark',
    npsCode: 'amsa',
    animals: [],
  },

  {
    id: 'virginislands',
    name: 'Virgin Islands National Park',
    state: 'US Virgin Islands',
    stateCodes: ['VI'],
    lat: 18.3413, lng: -64.7295,
    emoji: '🐢',
    locationType: 'nationalPark',
    npsCode: 'viis',
    animals: [],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // REMAINING MAINLAND PARKS
  // Animals populated entirely by live APIs (eBird · NPS · iNat · GBIF).
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'hotsprings',
    name: 'Hot Springs National Park',
    state: 'Arkansas',
    stateCodes: ['AR'],
    lat: 34.5220, lng: -93.0422,
    emoji: '♨️',
    locationType: 'nationalPark',
    npsCode: 'hosp',
    animals: [],
  },

  {
    id: 'carlsbadcaverns',
    name: 'Carlsbad Caverns National Park',
    state: 'New Mexico',
    stateCodes: ['NM'],
    lat: 32.1479, lng: -104.5567,
    emoji: '🦇',
    locationType: 'nationalPark',
    npsCode: 'cave',
    animals: [],
  },

  {
    id: 'greatbasin',
    name: 'Great Basin National Park',
    state: 'Nevada',
    stateCodes: ['NV'],
    lat: 38.9833, lng: -114.3000,
    emoji: '🦎',
    locationType: 'nationalPark',
    npsCode: 'grba',
    animals: [],
  },

];
